export const INSTALLMENT_PLANS_MAX = 5;
export const INSTALLMENT_PLAN_TITLE_MAX_LENGTH = 80;
export const INSTALLMENT_MONTHS_MIN = 2;
export const INSTALLMENT_MONTHS_MAX = 24;
export const INSTALLMENT_MONTHLY_PAYMENT_MIN_RUB = 100;
