/** Паритет `ProductQaSection.css` → `.product-qa-item` и потомков. */
export const PRODUCT_QA_ITEM_LAYOUT = {
  gap: 5.6,
  paddingVertical: 12,
  paddingHorizontal: 14,
  borderWidth: 1,
  borderRadius: 20,
  headMarginBottom: 2.4,
  authorFontSize: 14.4,
  dateFontSize: 12,
  questionFontSize: 14,
  questionLineHeight: 20.3,
  answerMarginTop: 2.4,
  answerGap: 3.2,
  answerPaddingVertical: 8,
  answerPaddingHorizontal: 10,
  answerBorderRadius: 10,
  answerBorderLeftWidth: 3,
  answerLabelFontSize: 11,
  answerLabelLetterSpacing: 0.22,
  answerTextFontSize: 14,
  answerTextLineHeight: 20.3,
  badgePaddingVertical: 1.6,
  badgePaddingHorizontal: 8,
  badgeFontSize: 11,
  hintFontSize: 12,
  actionsGap: 8,
  actionsMarginTop: 1.6,
  actionPaddingVertical: 4.8,
  actionPaddingHorizontal: 10.4,
  actionBorderRadius: 8,
  actionFontSize: 13,
} as const;
