/** Синхронизировано с client/src/shared/styles/designTokens.css (canonical v2) */
const izColorsCanonical = {
  text: "#111827",
  textMuted: "#6b7280",
  textSecondary: "#374151",
  textPlaceholder: "#9ca3af",
  ink: "#0f172a",
  bg: "#e5eef2",
  surface: "#ffffff",
  surfaceMuted: "#f9fafb",
  surfaceElevated: "#f8fafc",
  onContrast: "#ffffff",
  primary: "#284b7e",
  action: "#1f6feb",
  actionHover: "#1557b3",
  actionSoft: "#eff6ff",
  actionBorder: "#dbeafe",
  link: "#2563eb",
  success: "#16a34a",
  successSurface: "#f0fdf4",
  successText: "#047857",
  warning: "#d97706",
  warningSurface: "#fefce8",
  warningText: "#92400e",
  danger: "#c62828",
  dangerSurface: "#fef2f2",
  dangerText: "#991b1b",
  info: "#0369a1",
  infoSoft: "#f0f9ff",
  infoDeep: "#1e40af",
  border: "#e5e7eb",
  borderStrong: "#d1d5db",
  accent: "#7c3aed",
  accentSoft: "#ede9fe",
  overlay: "rgb(15 23 42 / 45%)",
  overlayStrong: "rgb(15 23 42 / 72%)",
  overlaySubtle: "rgb(17 24 39 / 8%)",
  focusRing: "rgb(31 111 235 / 15%)",
} as const;

const izColorsDarkCanonical = {
  text: "#f3f4f6",
  textMuted: "#9ca3af",
  textSecondary: "#d1d5db",
  textPlaceholder: "#9ca3af",
  ink: "#f8fafc",
  bg: "#0f172a",
  surface: "#1e293b",
  surfaceMuted: "#334155",
  surfaceElevated: "#1e293b",
  onContrast: "#0f172a",
  primary: "#93c5fd",
  action: "#3b82f6",
  actionHover: "#2563eb",
  actionSoft: "#172554",
  actionBorder: "#1e3a8a",
  link: "#60a5fa",
  success: "#4ade80",
  successSurface: "#064e3b",
  successText: "#86efac",
  warning: "#fbbf24",
  warningSurface: "#422006",
  warningText: "#fde68a",
  danger: "#f87171",
  dangerSurface: "#450a0a",
  dangerText: "#fecaca",
  info: "#38bdf8",
  infoSoft: "#0c4a6e",
  infoDeep: "#bfdbfe",
  border: "#334155",
  borderStrong: "#475569",
  accent: "#a78bfa",
  accentSoft: "#4c1d95",
  overlay: "rgb(0 0 0 / 55%)",
  overlayStrong: "rgb(0 0 0 / 72%)",
  overlaySubtle: "rgb(255 255 255 / 8%)",
  focusRing: "rgb(59 130 246 / 25%)",
} as const;

/** @deprecated mobile compat — merged into canonical tokens */
const izColorsCompat = {
  nearBlack: izColorsCanonical.ink,
  primaryBright: izColorsCanonical.action,
  actionSurface: izColorsCanonical.actionSoft,
  infoNavy: izColorsCanonical.infoDeep,
  premium: izColorsCanonical.warning,
  star: izColorsCanonical.warning,
  starMuted: izColorsCanonical.borderStrong,
  raffleSurface: izColorsCanonical.warningSurface,
  raffleBorder: izColorsCanonical.warning,
  warningBorder: izColorsCanonical.warning,
} as const;

const izColorsDarkCompat = {
  nearBlack: izColorsDarkCanonical.ink,
  primaryBright: izColorsDarkCanonical.action,
  actionSurface: izColorsDarkCanonical.actionSoft,
  infoNavy: izColorsDarkCanonical.infoDeep,
  premium: izColorsDarkCanonical.warning,
  star: izColorsDarkCanonical.warning,
  starMuted: izColorsDarkCanonical.borderStrong,
  raffleSurface: izColorsDarkCanonical.warningSurface,
  raffleBorder: izColorsDarkCanonical.warning,
  warningBorder: izColorsDarkCanonical.warning,
} as const;

export const izColors = {
  ...izColorsCanonical,
  ...izColorsCompat,
} as const;

export const izColorsDark = {
  ...izColorsDarkCanonical,
  ...izColorsDarkCompat,
} as const;
