/** Синхронизировано с client/src/shared/styles/designTokens.css (canonical v2) */
const izColorsCanonical = {
  text: "#111827",
  textMuted: "#6b7280",
  textSecondary: "#374151",
  textPlaceholder: "#9ca3af",
  ink: "#0f172a",
  bg: "#e5eef2",
  surface: "#ffffff",
  surfaceMuted: "#f9fafb",
  surfaceElevated: "#f8fafc",
  onContrast: "#ffffff",
  primary: "#284b7e",
  action: "#1f6feb",
  actionHover: "#1557b3",
  actionSoft: "#eff6ff",
  actionBorder: "#dbeafe",
  link: "#2563eb",
  success: "#16a34a",
  successSurface: "#f0fdf4",
  successText: "#047857",
  warning: "#d97706",
  warningSurface: "#fefce8",
  warningText: "#92400e",
  danger: "#c62828",
  dangerSurface: "#fef2f2",
  dangerText: "#991b1b",
  info: "#0369a1",
  infoSoft: "#f0f9ff",
  infoDeep: "#1e40af",
  border: "#e5e7eb",
  borderStrong: "#d1d5db",
  accent: "#7c3aed",
  accentSoft: "#ede9fe",
  overlay: "rgb(15 23 42 / 45%)",
  overlayStrong: "rgb(15 23 42 / 72%)",
  overlaySubtle: "rgb(17 24 39 / 8%)",
  focusRing: "rgb(31 111 235 / 15%)",
} as const;

/** Dark structural palette — chrome hues + white for readable text */
const darkPalette = {
  light: "#8589AC",
  mid: "#596F9A",
  deep: "#405577",
  surface: "#303147",
  bg: "#101115",
  white: "#ffffff",
} as const;

const izColorsDarkCanonical = {
  text: darkPalette.white,
  textMuted: darkPalette.light,
  textSecondary: darkPalette.white,
  textPlaceholder: darkPalette.mid,
  ink: darkPalette.white,
  bg: darkPalette.bg,
  surface: darkPalette.surface,
  surfaceMuted: darkPalette.deep,
  surfaceElevated: darkPalette.deep,
  onContrast: darkPalette.white,
  primary: darkPalette.light,
  action: darkPalette.mid,
  actionHover: darkPalette.light,
  actionSoft: darkPalette.deep,
  actionBorder: darkPalette.mid,
  link: darkPalette.light,
  success: "#4ade80",
  successSurface: "#064e3b",
  successText: "#86efac",
  warning: "#fbbf24",
  warningSurface: "#422006",
  warningText: "#fde68a",
  danger: "#f87171",
  dangerSurface: "#450a0a",
  dangerText: "#fecaca",
  info: "#38bdf8",
  infoSoft: "#0c4a6e",
  infoDeep: "#bfdbfe",
  border: darkPalette.deep,
  borderStrong: darkPalette.mid,
  accent: darkPalette.light,
  accentSoft: darkPalette.deep,
  overlay: "rgb(16 17 21 / 55%)",
  overlayStrong: "rgb(16 17 21 / 72%)",
  overlaySubtle: "rgb(133 137 172 / 8%)",
  focusRing: "rgb(89 111 154 / 25%)",
} as const;

/** @deprecated mobile compat — merged into canonical tokens */
const izColorsCompat = {
  nearBlack: izColorsCanonical.ink,
  primaryBright: izColorsCanonical.action,
  actionSurface: izColorsCanonical.actionSoft,
  infoNavy: izColorsCanonical.infoDeep,
  premium: izColorsCanonical.warning,
  star: izColorsCanonical.warning,
  starMuted: izColorsCanonical.borderStrong,
  raffleSurface: izColorsCanonical.warningSurface,
  raffleBorder: izColorsCanonical.warning,
  warningBorder: izColorsCanonical.warning,
} as const;

const izColorsDarkCompat = {
  nearBlack: izColorsDarkCanonical.ink,
  primaryBright: izColorsDarkCanonical.action,
  actionSurface: izColorsDarkCanonical.actionSoft,
  infoNavy: izColorsDarkCanonical.infoDeep,
  premium: izColorsDarkCanonical.warning,
  star: izColorsDarkCanonical.warning,
  starMuted: izColorsDarkCanonical.borderStrong,
  raffleSurface: izColorsDarkCanonical.warningSurface,
  raffleBorder: izColorsDarkCanonical.warning,
  warningBorder: izColorsDarkCanonical.warning,
} as const;

export const izColors = {
  ...izColorsCanonical,
  ...izColorsCompat,
} as const;

export const izColorsDark = {
  ...izColorsDarkCanonical,
  ...izColorsDarkCompat,
} as const;
