import {
  INSTALLMENT_CONTRACT_STATUS_ACTIVE,
  INSTALLMENT_CONTRACT_STATUS_PENDING_FIRST_PAYMENT,
} from "../../constants/installmentConstants.js";

export const ACTIVE_INSTALLMENT_CONTRACT_STATUSES = [
  INSTALLMENT_CONTRACT_STATUS_PENDING_FIRST_PAYMENT,
  INSTALLMENT_CONTRACT_STATUS_ACTIVE,
];
