export const USER_DATA_CONFIRMATION_STATUS_PENDING = "pending";
export const USER_DATA_CONFIRMATION_STATUS_APPROVED = "approved";
export const USER_DATA_CONFIRMATION_STATUS_REJECTED = "rejected";

export const USER_DATA_CONFIRMATION_RESOLUTION_APPROVE = "approve";
export const USER_DATA_CONFIRMATION_RESOLUTION_REJECT = "reject";
