/** Паритет client `AuthPage.css` + `AuthHeroBanner.css`. */
export const AUTH_PAGE_LAYOUT = {
  columnMaxWidth: 420,
  heroRadius: 32,
  bodyPaddingX: 24,
  bodyPaddingTop: 24,
  bodyPaddingBottom: 32,
  bodyGap: 8,
  formGap: 16,
  fieldGap: 6,
  titleFontSize: 26,
  subtitleFontSize: 15,
  subtitleLineHeight: 20,
  subtitleMarginBottom: 8,
  labelFontSize: 13,
  inputFontSize: 15,
  inputPaddingY: 12,
  inputPaddingX: 14,
  inputRadius: 10,
  backSize: 40,
  backTopInset: 8,
  backLeftInset: 16,
  backRadius: 10,
  channelGap: 8,
  channelBtnRadius: 8,
  channelBtnPaddingY: 7,
  channelBtnPaddingX: 10,
  channelBtnFontSize: 14,
  linkFontSize: 14,
  errorFontSize: 14,
  passwordToggleSize: 18,
} as const;
