export const PRODUCT_MANAGE_TOGGLE_ROW_BORDER_RADIUS = 40;
export const PRODUCT_MANAGE_TOGGLE_ROW_MIN_HEIGHT = 72;
export const PRODUCT_MANAGE_TOGGLE_ROW_ARTWORK_WIDTH = 88;
export const PRODUCT_MANAGE_TOGGLE_ROW_ARTWORK_HEIGHT = 56;
