/** SSOT: `contract/src/productQuestion.js`. */
export {
  PRODUCT_QUESTION_TEXT_MAX_LENGTH,
  PRODUCT_ANSWER_TEXT_MAX_LENGTH,
  PRODUCT_QUESTION_LIMIT_DEFAULT as PRODUCT_QUESTION_PAGE_LIMIT,
  PRODUCT_QUESTIONS_MAX_PER_PRODUCT,
  PRODUCT_QUESTION_STATUS_PENDING,
  PRODUCT_QUESTION_STATUS_ANSWERED,
  PRODUCT_QUESTION_STATUS_HIDDEN,
} from "@molha/api-contract";
