export const PRODUCT_QUESTION_TEXT_MAX_LENGTH = 300;
export const PRODUCT_ANSWER_TEXT_MAX_LENGTH = 300;
export const PRODUCT_QUESTION_PAGE_LIMIT = 20;
export const PRODUCT_QUESTIONS_MAX_PER_PRODUCT = 50;

export const PRODUCT_QUESTION_STATUS_PENDING = "pending";
export const PRODUCT_QUESTION_STATUS_ANSWERED = "answered";
export const PRODUCT_QUESTION_STATUS_HIDDEN = "hidden";
