export const ONEC_INTEGRATION_PAGE_UI = {
  TITLE: "Интеграция с 1С",
  LEAD:
    "Подключите HTTP-сервис своей 1С: товары, цены и остатки будут приходить на сайт, а заказы клиентов уходить в «Заказ покупателя».",
  AUTH_REQUIRED: "Войдите, чтобы настроить интеграцию с 1С",
  LOGIN_BUTTON: "Войти",
  LABEL_ENABLED: "Обмен включён",
  LABEL_BASE_URL: "URL HTTP-сервиса 1С",
  PLACEHOLDER_BASE_URL: "https://ваш-сервер/onec-api",
  LABEL_API_KEY: "API-ключ",
  PLACEHOLDER_API_KEY: "Вставьте ключ (сохраняется в зашифрованном виде)",
  HINT_API_KEY_SET: "Ключ сохранён:",
  HINT_LEAVE_KEY: "Оставьте поле пустым, чтобы не менять сохранённый ключ.",
  SAVE: "Сохранить",
  SAVE_PENDING: "Сохраняем…",
  TEST: "Проверить соединение",
  TEST_PENDING: "Проверяем…",
  SYNC: "Обменять сейчас",
  SYNC_PENDING: "Обмен…",
  DISCONNECT: "Отключить 1С",
  DISCONNECT_CONFIRM: "Отключить интеграцию и удалить ключ?",
  STATUS_IDLE: "Ещё не было обмена",
  STATUS_SUCCESS: "Последний обмен успешен",
  STATUS_ERROR: "Последний обмен с ошибкой",
  LOGS_TITLE: "Журнал обмена",
  LOGS_EMPTY: "Записей пока нет",
  LOADING: "Загрузка…",
  MOCK_HINT:
    "Для локального теста: в папке server выполните npm run onec:mock, URL http://127.0.0.1:3091, ключ mock-onec-key",
};
