import { useMemo } from "react";

import { useAppShellStateContext } from "./AppShellStateContext.jsx";

/** @typedef {import('../../../entities/product/model/types.js').ProductFromApi} ProductFromApi */

export const useHomeCatalogGridProps = () => {
  const ctx = useAppShellStateContext();
  const {
    catalogStatus,
    products,
    showHomeCatalogFeed,
    featuredRaffles,
    getFeaturedRaffleManage,
    userStoriesFeed,
    isAuthorized,
    currentUserId,
    handleUserStoriesRefresh,
    handleSellerNameClick,
    catalogMainView,
    activeCatalogBrowserCategory,
    selectedProductCategory,
    hasProductSearchQuery,
    isMineMode,
    deletingProductId,
    handleDeleteMyProduct,
    handleOpenEditMyProduct,
    handleOpenPromotionModal,
    myProductsCatalogError,
    myProductsCatalogNotice,
    handleOpenCatalogProductDetails,
    handleSetMyProductAvailability,
    handleSetProductAuction,
    togglingAvailabilityProductId,
    togglingAuctionProductId,
    isPremiumUser,
    loyaltyPoints,
    loyaltyPointsReserved,
    setIsLoginModalOpen,
    catalogSentinelRef,
    catalogHasMore,
    isCatalogLoadingMore,
    catalogLoadMoreError,
    handleRetryCatalogLoadMore,
    myProductsModerationFilter,
    catalogFollowingOnly,
    catalogAuctionOnly,
    catalogInstallmentOnly,
    catalogSaleOnly,
    catalogRentalOnly,
    catalogAffiliateOnly,
    catalogWholesaleOnly,
    catalogOriginalOnly,
    catalogNear,
    authUser,
    sellerRaffleActive,
    raffleParticipationPendingProductId,
    homeCuratedProductLists,
    showCuratedProductLists,
    curatedListsQuery,
    handlePlaceProductClick,
    viewerRegionCode,
  } = ctx;

  const isCuratedProductListsLoading =
    showCuratedProductLists && curatedListsQuery.isPending;
  const isUserDataConfirmed = authUser?.isUserDataConfirmed === true;

  return useMemo(
    () => ({
      catalogStatus,
      products,
      isHomeCatalogMainView: Boolean(showHomeCatalogFeed),
      featuredRaffles,
      getFeaturedRaffleManage,
      userStoriesFeed,
      isAuthorized,
      currentUserId,
      onUserStoriesRefresh: handleUserStoriesRefresh,
      onSellerNameClick: handleSellerNameClick,
      catalogMainView,
      activeCatalogBrowserCategory,
      selectedProductCategory,
      hasProductSearchQuery,
      isMineMode,
      deletingProductId,
      onDeleteMyProduct: handleDeleteMyProduct,
      onEditMyProduct: handleOpenEditMyProduct,
      onPromoteMyProduct: handleOpenPromotionModal,
      myProductsCatalogError,
      myProductsCatalogNotice,
      onOpenProductDetails: handleOpenCatalogProductDetails,
      onSetMyProductAvailability: handleSetMyProductAvailability,
      onSetMyProductAuction: handleSetProductAuction,
      togglingAvailabilityProductId,
      togglingAuctionProductId,
      isPremiumUser,
      sellerLoyaltyPointsBalance: loyaltyPoints,
      sellerLoyaltyPointsReserved: loyaltyPointsReserved,
      onRequestLoginAddToCart: () => setIsLoginModalOpen(true),
      catalogSentinelRef,
      catalogHasMore,
      isCatalogLoadingMore,
      catalogLoadMoreError,
      onRetryCatalogLoadMore: handleRetryCatalogLoadMore,
      myProductsModerationFilter,
      catalogFollowingOnly,
      catalogAuctionOnly,
      catalogInstallmentOnly,
      catalogSaleOnly,
      catalogRentalOnly,
      catalogAffiliateOnly,
      catalogWholesaleOnly,
      catalogOriginalOnly,
      catalogNear,
      showFullWidthTier3Banners: Boolean(showHomeCatalogFeed) && !isMineMode,
      viewerRegionCode,
      sellerRaffleActive,
      raffleParticipationPendingProductId,
      homeCuratedProductLists,
      showCuratedProductLists,
      isCuratedProductListsLoading,
      isUserDataConfirmed,
      onPlaceProductClick: handlePlaceProductClick,
    }),
    [
      catalogStatus,
      products,
      showHomeCatalogFeed,
      featuredRaffles,
      getFeaturedRaffleManage,
      userStoriesFeed,
      isAuthorized,
      currentUserId,
      handleUserStoriesRefresh,
      handleSellerNameClick,
      catalogMainView,
      activeCatalogBrowserCategory,
      selectedProductCategory,
      hasProductSearchQuery,
      isMineMode,
      deletingProductId,
      handleDeleteMyProduct,
      handleOpenEditMyProduct,
      handleOpenPromotionModal,
      myProductsCatalogError,
      myProductsCatalogNotice,
      handleOpenCatalogProductDetails,
      handleSetMyProductAvailability,
      handleSetProductAuction,
      togglingAvailabilityProductId,
      togglingAuctionProductId,
      isPremiumUser,
      loyaltyPoints,
      loyaltyPointsReserved,
      setIsLoginModalOpen,
      catalogSentinelRef,
      catalogHasMore,
      isCatalogLoadingMore,
      catalogLoadMoreError,
      handleRetryCatalogLoadMore,
      myProductsModerationFilter,
      catalogFollowingOnly,
      catalogAuctionOnly,
      catalogInstallmentOnly,
      catalogSaleOnly,
      catalogRentalOnly,
      catalogAffiliateOnly,
      catalogWholesaleOnly,
      catalogOriginalOnly,
      catalogNear,
      sellerRaffleActive,
      raffleParticipationPendingProductId,
      homeCuratedProductLists,
      showCuratedProductLists,
      isCuratedProductListsLoading,
      isUserDataConfirmed,
      handlePlaceProductClick,
      viewerRegionCode,
    ],
  );
};
