import { useCallback, useMemo } from "react";

import { useAppShellStateContext } from "./AppShellStateContext.jsx";

export const useHomeMainContentProps = () => {
  const ctx = useAppShellStateContext();
  const {
    isAuthorized,
    isSessionReady,
    mainView,
    activeProfileTab,
    currentUserId,
    isPremiumUser,
    isAdmin,
    canModerateProducts,
    myProfilePage,
    notificationsPageItems,
    pendingRafflesCount,
    pendingProductPromotionsCount,
    pendingModerationCount,
    pendingIntroAdModerationCount,
    pendingSellerPersonalCategoryModerationCount,
    pendingIncomingPriceOffersCount,
    pendingMySalesActionCount,
    pendingMyOrdersActionCount,
    pendingInstallmentBuyerActionCount,
    pendingInstallmentSellerActionCount,
    pendingInstallmentModerationCount,
    pendingInstallmentDisputesCount,
    pendingProductReportsCount,
    pendingDataConfirmationCount,
    catalogSort,
    handleCatalogSortChange,
    myProductsTotal,
    sellerProductsLimit,
    myProductsModerationFilter,
    setMyProductsModerationFilter,
    setIsLoginModalOpen,
    handleSellerNameClick,
    handleCatalogProductClick,
    handleOpenCatalogProductDetails,
    setCatalogProductDetails,
    setMyProfileTab,
    handleLogout,
    setIsEditProfileOpen,
    handleMyProductsFromProfile,
    handleMySalesFromProfile,
    handleInstallmentPaymentsFromProfile,
    handleInstallmentSalesFromProfile,
    handleInstallmentModerationFromProfile,
    handleInstallmentDisputesFromProfile,
    handleMyOrdersFromProfile,
    handleAuctionFromProfile,
    handleAdminOrdersFromProfile,
    handleSearchSynonymsAdminFromProfile,
    handleCategoryTreeAdminFromProfile,
    handleAppIntroAdminFromProfile,
    handleSiteHeaderBannerAdminFromProfile,
    handlePopularProductsAdminFromProfile,
    handleProductModerationFromProfile,
    handleProductReportsFromProfile,
    handleProductPromotionsFromProfile,
    handleRafflesFromProfile,
    setRaffleModal,
    handleDataConfirmationQueueFromProfile,
    handleDataConfirmationFromProfile,
    setIsDataConfirmationModalOpen,
    handlePremiumFromProfile,
    handlePremiumPurchased,
    handleLoyaltyPointsFromProfile,
    handleAdvertisingFromProfile,
    handleIntroAdModerationFromProfile,
    handleSellerPersonalCategoryModerationFromProfile,
    handleSubscriptionsFromProfile,
    handleWishlistFromProfile,
    refreshUserProfileActionBadgeCounts,
    refreshPendingModerationCount,
    refreshPendingIntroAdModerationCount,
    refreshPendingSellerPersonalCategoryModerationCount,
    refreshPendingProductReportsCount,
    refreshPendingProductPromotionsCount,
    refreshPendingRafflesCount,
    refreshPendingDataConfirmationCount,
    refreshPendingInstallmentModerationCount,
    refreshPendingInstallmentDisputesCount,
    refreshRaffleSurfaces,
    refreshCatalogFeed,
    handleInAppNotificationClick,
    handleNotificationsCleared,
  } = ctx;

  const myProductsCatalogToolbarProps = useMemo(
    () => ({
      catalogSort,
      onCatalogSortChange: handleCatalogSortChange,
      isAdmin,
      myProductsTotal,
      sellerProductsLimit,
      myProductsModerationFilter,
      onMyProductsModerationFilterChange: setMyProductsModerationFilter,
    }),
    [
      catalogSort,
      handleCatalogSortChange,
      isAdmin,
      myProductsTotal,
      sellerProductsLimit,
      myProductsModerationFilter,
      setMyProductsModerationFilter,
    ],
  );

  const onRequestLogin = useCallback(() => {
    setIsLoginModalOpen(true);
  }, [setIsLoginModalOpen]);

  const onEditProfileClick = useCallback(() => {
    setIsEditProfileOpen(true);
  }, [setIsEditProfileOpen]);

  const onCreateRaffleClick = useMemo(() => {
    if (
      myProfilePage.phase === "success" &&
      myProfilePage.user?.isUserDataConfirmed === true
    ) {
      return () => setRaffleModal({ mode: "create" });
    }
    return undefined;
  }, [myProfilePage, setRaffleModal]);

  return useMemo(
    () => ({
      isAuthorized,
      isSessionReady,
      mainView,
      activeProfileTab,
      currentUserId,
      isPremiumUser,
      isAdmin,
      canModerateProducts,
      myProfilePage,
      notificationsPageItems,
      pendingRafflesCount,
      pendingProductPromotionsCount,
      pendingModerationCount,
      pendingIntroAdModerationCount,
      pendingSellerPersonalCategoryModerationCount,
      pendingIncomingPriceOffersCount,
      pendingMySalesActionCount,
      pendingMyOrdersActionCount,
      pendingInstallmentBuyerActionCount,
      pendingInstallmentSellerActionCount,
      pendingInstallmentModerationCount,
      pendingInstallmentDisputesCount,
      pendingProductReportsCount,
      pendingDataConfirmationCount,
      myProductsCatalogToolbarProps,
      onRequestLogin,
      onSellerNameClick: handleSellerNameClick,
      onCatalogProductClick: handleCatalogProductClick,
      onOpenProductDetails: handleOpenCatalogProductDetails,
      setMyProfileTab,
      handleLogout,
      onEditProfileClick,
      handleMyProductsFromProfile,
      handleMySalesFromProfile,
      handleInstallmentPaymentsFromProfile,
      handleInstallmentSalesFromProfile,
      handleInstallmentModerationFromProfile,
      handleInstallmentDisputesFromProfile,
      handleMyOrdersFromProfile,
      handleAuctionFromProfile,
      handleAdminOrdersFromProfile,
      handleSearchSynonymsAdminFromProfile,
      handleCategoryTreeAdminFromProfile,
      handleAppIntroAdminFromProfile,
      handleSiteHeaderBannerAdminFromProfile,
      handlePopularProductsAdminFromProfile,
      handleProductModerationFromProfile,
      handleProductReportsFromProfile,
      handleProductPromotionsFromProfile,
      handleRafflesFromProfile,
      onCreateRaffleClick,
      handleDataConfirmationQueueFromProfile,
      handleDataConfirmationFromProfile,
      setIsDataConfirmationModalOpen,
      handlePremiumFromProfile,
      handlePremiumPurchased,
      handleLoyaltyPointsFromProfile,
      handleAdvertisingFromProfile,
      handleIntroAdModerationFromProfile,
      handleSellerPersonalCategoryModerationFromProfile,
      handleSubscriptionsFromProfile,
      handleWishlistFromProfile,
      refreshUserProfileActionBadgeCounts,
      refreshPendingModerationCount,
      refreshPendingIntroAdModerationCount,
      refreshPendingSellerPersonalCategoryModerationCount,
      refreshPendingProductReportsCount,
      refreshPendingProductPromotionsCount,
      refreshPendingRafflesCount,
      refreshPendingDataConfirmationCount,
      refreshPendingInstallmentModerationCount,
      refreshPendingInstallmentDisputesCount,
      refreshRaffleSurfaces,
      refreshCatalogFeed,
      setRaffleModal,
      handleInAppNotificationClick,
      handleNotificationsCleared,
    }),
    [
      isAuthorized,
      isSessionReady,
      mainView,
      activeProfileTab,
      currentUserId,
      isPremiumUser,
      isAdmin,
      canModerateProducts,
      myProfilePage,
      notificationsPageItems,
      pendingRafflesCount,
      pendingProductPromotionsCount,
      pendingModerationCount,
      pendingIntroAdModerationCount,
      pendingSellerPersonalCategoryModerationCount,
      pendingIncomingPriceOffersCount,
      pendingMySalesActionCount,
      pendingMyOrdersActionCount,
      pendingInstallmentBuyerActionCount,
      pendingInstallmentSellerActionCount,
      pendingInstallmentModerationCount,
      pendingInstallmentDisputesCount,
      pendingProductReportsCount,
      pendingDataConfirmationCount,
      myProductsCatalogToolbarProps,
      onRequestLogin,
      handleSellerNameClick,
      handleCatalogProductClick,
      handleOpenCatalogProductDetails,
      setCatalogProductDetails,
      setMyProfileTab,
      handleLogout,
      onEditProfileClick,
      handleMyProductsFromProfile,
      handleMySalesFromProfile,
      handleInstallmentPaymentsFromProfile,
      handleInstallmentSalesFromProfile,
      handleInstallmentModerationFromProfile,
      handleInstallmentDisputesFromProfile,
      handleMyOrdersFromProfile,
      handleAuctionFromProfile,
      handleAdminOrdersFromProfile,
      handleSearchSynonymsAdminFromProfile,
      handleCategoryTreeAdminFromProfile,
      handleAppIntroAdminFromProfile,
      handleSiteHeaderBannerAdminFromProfile,
      handlePopularProductsAdminFromProfile,
      handleProductModerationFromProfile,
      handleProductReportsFromProfile,
      handleProductPromotionsFromProfile,
      handleRafflesFromProfile,
      onCreateRaffleClick,
      handleDataConfirmationQueueFromProfile,
      handleDataConfirmationFromProfile,
      setIsDataConfirmationModalOpen,
      handlePremiumFromProfile,
      handlePremiumPurchased,
      handleLoyaltyPointsFromProfile,
      handleAdvertisingFromProfile,
      handleIntroAdModerationFromProfile,
      handleSellerPersonalCategoryModerationFromProfile,
      handleSubscriptionsFromProfile,
      handleWishlistFromProfile,
      refreshUserProfileActionBadgeCounts,
      refreshPendingModerationCount,
      refreshPendingIntroAdModerationCount,
      refreshPendingSellerPersonalCategoryModerationCount,
      refreshPendingProductReportsCount,
      refreshPendingProductPromotionsCount,
      refreshPendingRafflesCount,
      refreshPendingDataConfirmationCount,
      refreshPendingInstallmentModerationCount,
      refreshPendingInstallmentDisputesCount,
      refreshRaffleSurfaces,
      refreshCatalogFeed,
      setRaffleModal,
      handleInAppNotificationClick,
      handleNotificationsCleared,
    ],
  );
};
