import { useCallback, useMemo } from "react";

import { PROFILE_TAB_OVERVIEW } from "../lib/profileTabs.js";
import { useAppShellStateContext } from "./AppShellStateContext.jsx";

export const useHomeMainContentProps = () => {
  const ctx = useAppShellStateContext();
  const {
    isAuthorized,
    isSessionReady,
    mainView,
    activeProfileTab,
    currentUserId,
    isPremiumUser,
    isAdmin,
    canModerateProducts,
    myProfilePage,
    setMyProfilePage,
    notificationsPageItems,
    pendingRafflesCount,
    pendingProductPromotionsCount,
    pendingModerationCount,
    pendingIntroAdModerationCount,
    pendingSellerPersonalCategoryModerationCount,
    pendingIncomingPriceOffersCount,
    pendingMySalesActionCount,
    pendingMyOrdersActionCount,
    pendingInstallmentBuyerActionCount,
    pendingInstallmentSellerActionCount,
    pendingInstallmentDisputesCount,
    pendingProductReportsCount,
    pendingDataConfirmationCount,
    catalogSort,
    handleCatalogSortChange,
    myProductsTotal,
    sellerProductsLimit,
    myProductsModerationFilter,
    setMyProductsModerationFilter,
    setIsLoginModalOpen,
    handleSellerNameClick,
    handleCatalogProductClick,
    handleOpenCatalogProductDetails,
    setMyProfileTab,
    handleLogout,
    handleMyProductsFromProfile,
    handleMySalesFromProfile,
    handleInstallmentPaymentsFromProfile,
    handleInstallmentSalesFromProfile,
    handleInstallmentDisputesFromProfile,
    handleMyOrdersFromProfile,
    handleAuctionFromProfile,
    handleAdminOrdersFromProfile,
    handleSearchSynonymsAdminFromProfile,
    handleCategoryTreeAdminFromProfile,
    handleAppIntroAdminFromProfile,
    handleSiteHeaderBannerAdminFromProfile,
    handlePopularProductsAdminFromProfile,
    handleProductModerationFromProfile,
    handleProductReportsFromProfile,
    handleProductPromotionsFromProfile,
    handleRafflesFromProfile,
    setRaffleModal,
    handleDataConfirmationQueueFromProfile,
    handleDataConfirmationFromProfile,
    setIsDataConfirmationModalOpen,
    handlePremiumFromProfile,
    handlePremiumPurchased,
    handleLoyaltyPointsFromProfile,
    handlePartnerProgramFromProfile,
    handleAdvertisingFromProfile,
    handleOneCIntegrationFromProfile,
    handleEditProfileFromProfile,
    handleIntroAdModerationFromProfile,
    handleSellerPersonalCategoryModerationFromProfile,
    handleSubscriptionsFromProfile,
    handleWishlistFromProfile,
    refreshUserProfileActionBadgeCounts,
    refreshPendingModerationCount,
    refreshPendingIntroAdModerationCount,
    refreshPendingSellerPersonalCategoryModerationCount,
    refreshPendingProductReportsCount,
    refreshPendingProductPromotionsCount,
    refreshPendingRafflesCount,
    refreshPendingDataConfirmationCount,
    refreshPendingInstallmentDisputesCount,
    refreshRaffleSurfaces,
    refreshCatalogFeed,
    invalidateAuthMe,
    handleInAppNotificationClick,
    handleNotificationsCleared,
    setLoyaltyPoints,
    setIsPremiumUser,
  } = ctx;

  const myProductsCatalogToolbarProps = useMemo(
    () => ({
      catalogSort,
      onCatalogSortChange: handleCatalogSortChange,
      isAdmin,
      myProductsTotal,
      sellerProductsLimit,
      myProductsModerationFilter,
      onMyProductsModerationFilterChange: setMyProductsModerationFilter,
    }),
    [
      catalogSort,
      handleCatalogSortChange,
      isAdmin,
      myProductsTotal,
      sellerProductsLimit,
      myProductsModerationFilter,
      setMyProductsModerationFilter,
    ],
  );

  const onRequestLogin = useCallback(() => {
    setIsLoginModalOpen(true);
  }, [setIsLoginModalOpen]);

  const onEditProfileClick = handleEditProfileFromProfile;

  const onEditProfileCancel = useCallback(() => {
    setMyProfileTab(PROFILE_TAB_OVERVIEW);
  }, [setMyProfileTab]);

  const onEditProfileSaved = useCallback(
    (updatedUser) => {
      setMyProfilePage((prev) =>
        prev.phase === "success" && prev.user
          ? { ...prev, user: { ...prev.user, ...updatedUser } }
          : prev,
      );
      if (updatedUser.isPremiumUser !== undefined) {
        setIsPremiumUser(Boolean(updatedUser.isPremiumUser));
      }
      if (updatedUser.userLoyaltyPoints != null) {
        setLoyaltyPoints(Number(updatedUser.userLoyaltyPoints) || 0);
      }
      void invalidateAuthMe();
      void refreshCatalogFeed();
    },
    [
      invalidateAuthMe,
      refreshCatalogFeed,
      setIsPremiumUser,
      setLoyaltyPoints,
      setMyProfilePage,
    ],
  );

  const onCreateRaffleClick = useMemo(() => {
    if (
      myProfilePage.phase === "success" &&
      myProfilePage.user?.isUserDataConfirmed === true
    ) {
      return () => setRaffleModal({ mode: "create" });
    }
    return undefined;
  }, [myProfilePage, setRaffleModal]);

  return useMemo(
    () => ({
      isAuthorized,
      isSessionReady,
      mainView,
      activeProfileTab,
      currentUserId,
      isPremiumUser,
      isAdmin,
      canModerateProducts,
      myProfilePage,
      notificationsPageItems,
      pendingRafflesCount,
      pendingProductPromotionsCount,
      pendingModerationCount,
      pendingIntroAdModerationCount,
      pendingSellerPersonalCategoryModerationCount,
      pendingIncomingPriceOffersCount,
      pendingMySalesActionCount,
      pendingMyOrdersActionCount,
      pendingInstallmentBuyerActionCount,
      pendingInstallmentSellerActionCount,
      pendingInstallmentDisputesCount,
      pendingProductReportsCount,
      pendingDataConfirmationCount,
      myProductsCatalogToolbarProps,
      onRequestLogin,
      onSellerNameClick: handleSellerNameClick,
      onCatalogProductClick: handleCatalogProductClick,
      onOpenProductDetails: handleOpenCatalogProductDetails,
      setMyProfileTab,
      handleLogout,
      onEditProfileClick,
      onEditProfileCancel,
      onEditProfileSaved,
      handleMyProductsFromProfile,
      handleMySalesFromProfile,
      handleInstallmentPaymentsFromProfile,
      handleInstallmentSalesFromProfile,
      handleInstallmentDisputesFromProfile,
      handleMyOrdersFromProfile,
      handleAuctionFromProfile,
      handleAdminOrdersFromProfile,
      handleSearchSynonymsAdminFromProfile,
      handleCategoryTreeAdminFromProfile,
      handleAppIntroAdminFromProfile,
      handleSiteHeaderBannerAdminFromProfile,
      handlePopularProductsAdminFromProfile,
      handleProductModerationFromProfile,
      handleProductReportsFromProfile,
      handleProductPromotionsFromProfile,
      handleRafflesFromProfile,
      onCreateRaffleClick,
      handleDataConfirmationQueueFromProfile,
      handleDataConfirmationFromProfile,
      setIsDataConfirmationModalOpen,
      handlePremiumFromProfile,
      handlePremiumPurchased,
      handleLoyaltyPointsFromProfile,
      handlePartnerProgramFromProfile,
      handleAdvertisingFromProfile,
      handleOneCIntegrationFromProfile,
      handleIntroAdModerationFromProfile,
      handleSellerPersonalCategoryModerationFromProfile,
      handleSubscriptionsFromProfile,
      handleWishlistFromProfile,
      refreshUserProfileActionBadgeCounts,
      refreshPendingModerationCount,
      refreshPendingIntroAdModerationCount,
      refreshPendingSellerPersonalCategoryModerationCount,
      refreshPendingProductReportsCount,
      refreshPendingProductPromotionsCount,
      refreshPendingRafflesCount,
      refreshPendingDataConfirmationCount,
      refreshPendingInstallmentDisputesCount,
      refreshRaffleSurfaces,
      refreshCatalogFeed,
      setRaffleModal,
      setLoyaltyPoints,
      handleInAppNotificationClick,
      handleNotificationsCleared,
    }),
    [
      isAuthorized,
      isSessionReady,
      mainView,
      activeProfileTab,
      currentUserId,
      isPremiumUser,
      isAdmin,
      canModerateProducts,
      myProfilePage,
      notificationsPageItems,
      pendingRafflesCount,
      pendingProductPromotionsCount,
      pendingModerationCount,
      pendingIntroAdModerationCount,
      pendingSellerPersonalCategoryModerationCount,
      pendingIncomingPriceOffersCount,
      pendingMySalesActionCount,
      pendingMyOrdersActionCount,
      pendingInstallmentBuyerActionCount,
      pendingInstallmentSellerActionCount,
      pendingInstallmentDisputesCount,
      pendingProductReportsCount,
      pendingDataConfirmationCount,
      myProductsCatalogToolbarProps,
      onRequestLogin,
      handleSellerNameClick,
      handleCatalogProductClick,
      handleOpenCatalogProductDetails,
      setMyProfileTab,
      handleLogout,
      onEditProfileClick,
      onEditProfileCancel,
      onEditProfileSaved,
      handleMyProductsFromProfile,
      handleMySalesFromProfile,
      handleInstallmentPaymentsFromProfile,
      handleInstallmentSalesFromProfile,
      handleInstallmentDisputesFromProfile,
      handleMyOrdersFromProfile,
      handleAuctionFromProfile,
      handleAdminOrdersFromProfile,
      handleSearchSynonymsAdminFromProfile,
      handleCategoryTreeAdminFromProfile,
      handleAppIntroAdminFromProfile,
      handleSiteHeaderBannerAdminFromProfile,
      handlePopularProductsAdminFromProfile,
      handleProductModerationFromProfile,
      handleProductReportsFromProfile,
      handleProductPromotionsFromProfile,
      handleRafflesFromProfile,
      onCreateRaffleClick,
      handleDataConfirmationQueueFromProfile,
      handleDataConfirmationFromProfile,
      setIsDataConfirmationModalOpen,
      handlePremiumFromProfile,
      handlePremiumPurchased,
      handleLoyaltyPointsFromProfile,
      handlePartnerProgramFromProfile,
      handleAdvertisingFromProfile,
      handleOneCIntegrationFromProfile,
      handleIntroAdModerationFromProfile,
      handleSellerPersonalCategoryModerationFromProfile,
      handleSubscriptionsFromProfile,
      handleWishlistFromProfile,
      refreshUserProfileActionBadgeCounts,
      refreshPendingModerationCount,
      refreshPendingIntroAdModerationCount,
      refreshPendingSellerPersonalCategoryModerationCount,
      refreshPendingProductReportsCount,
      refreshPendingProductPromotionsCount,
      refreshPendingRafflesCount,
      refreshPendingDataConfirmationCount,
      refreshPendingInstallmentDisputesCount,
      refreshRaffleSurfaces,
      refreshCatalogFeed,
      setRaffleModal,
      setLoyaltyPoints,
      handleInAppNotificationClick,
      handleNotificationsCleared,
    ],
  );
};
