import { useMemo } from "react";

import { useAppShellStateContext } from "./AppShellStateContext.jsx";
import { CATALOG_SORT_CITY } from "../../../entities/product/model/productConstants.js";

/** @typedef {import('../../../entities/product/model/types.js').ProductFromApi} ProductFromApi */

export const useHomeCatalogGridProps = () => {
  const ctx = useAppShellStateContext();
  const {
    catalogStatus,
    products,
    isHomeCatalogMainView,
    featuredRaffles,
    getFeaturedRaffleManage,
    userStoriesFeed,
    isAuthorized,
    currentUserId,
    handleUserStoriesRefresh,
    handleSellerNameClick,
    catalogMainView,
    activeCatalogBrowserCategory,
    selectedProductCategory,
    hasProductSearchQuery,
    isMineMode,
    deletingProductId,
    handleDeleteMyProduct,
    handleOpenEditMyProduct,
    handleOpenPromotionModal,
    myProductsCatalogError,
    myProductsCatalogNotice,
    handleOpenCatalogProductDetails,
    handleSetMyProductAvailability,
    handleSetProductAuction,
    togglingAvailabilityProductId,
    togglingAuctionProductId,
    isPremiumUser,
    loyaltyPoints,
    loyaltyPointsReserved,
    setIsLoginModalOpen,
    catalogSentinelRef,
    catalogHasMore,
    isCatalogLoadingMore,
    catalogLoadMoreError,
    handleRetryCatalogLoadMore,
    myProductsModerationFilter,
    catalogFollowingOnly,
    catalogAuctionOnly,
    catalogInstallmentOnly,
    catalogSaleOnly,
    catalogAllCities,
    catalogSort,
    authUser,
    handleShowAllCatalogCities,
    sellerRaffleActive,
    raffleParticipationPendingProductId,
    homeCuratedProductLists,
    showCuratedProductLists,
    curatedListsQuery,
  } = ctx;

  const catalogCityFilterLabel = String(authUser?.userAddressCity ?? "").trim();
  const isCuratedProductListsLoading =
    showCuratedProductLists && curatedListsQuery.isPending;

  return useMemo(
    () => ({
      catalogStatus,
      products,
      isHomeCatalogMainView,
      featuredRaffles,
      getFeaturedRaffleManage,
      userStoriesFeed,
      isAuthorized,
      currentUserId,
      onUserStoriesRefresh: handleUserStoriesRefresh,
      onSellerNameClick: handleSellerNameClick,
      catalogMainView,
      activeCatalogBrowserCategory,
      selectedProductCategory,
      hasProductSearchQuery,
      isMineMode,
      deletingProductId,
      onDeleteMyProduct: handleDeleteMyProduct,
      onEditMyProduct: handleOpenEditMyProduct,
      onPromoteMyProduct: handleOpenPromotionModal,
      myProductsCatalogError,
      myProductsCatalogNotice,
      onOpenProductDetails: handleOpenCatalogProductDetails,
      onSetMyProductAvailability: handleSetMyProductAvailability,
      onSetMyProductAuction: handleSetProductAuction,
      togglingAvailabilityProductId,
      togglingAuctionProductId,
      isPremiumUser,
      sellerLoyaltyPointsBalance: loyaltyPoints,
      sellerLoyaltyPointsReserved: loyaltyPointsReserved,
      onRequestLoginAddToCart: () => setIsLoginModalOpen(true),
      catalogSentinelRef,
      catalogHasMore,
      isCatalogLoadingMore,
      catalogLoadMoreError,
      onRetryCatalogLoadMore: handleRetryCatalogLoadMore,
      myProductsModerationFilter,
      catalogFollowingOnly,
      catalogAuctionOnly,
      catalogInstallmentOnly,
      catalogSaleOnly,
      showCatalogCityFilterBanner:
        isAuthorized &&
        !isMineMode &&
        catalogCityFilterLabel !== "" &&
        !catalogAllCities &&
        catalogSort !== CATALOG_SORT_CITY,
      catalogCityFilterLabel,
      onShowAllCatalogCities: handleShowAllCatalogCities,
      showFullWidthTier3Banners:
        !isMineMode &&
        !selectedProductCategory &&
        !hasProductSearchQuery &&
        !catalogFollowingOnly &&
        !catalogAuctionOnly &&
        !catalogInstallmentOnly &&
        !catalogSaleOnly,
      sellerRaffleActive,
      raffleParticipationPendingProductId,
      homeCuratedProductLists,
      showCuratedProductLists,
      isCuratedProductListsLoading,
    }),
    [
      catalogStatus,
      products,
      isHomeCatalogMainView,
      featuredRaffles,
      getFeaturedRaffleManage,
      userStoriesFeed,
      isAuthorized,
      currentUserId,
      handleUserStoriesRefresh,
      handleSellerNameClick,
      catalogMainView,
      activeCatalogBrowserCategory,
      selectedProductCategory,
      hasProductSearchQuery,
      isMineMode,
      deletingProductId,
      handleDeleteMyProduct,
      handleOpenEditMyProduct,
      handleOpenPromotionModal,
      myProductsCatalogError,
      myProductsCatalogNotice,
      handleOpenCatalogProductDetails,
      handleSetMyProductAvailability,
      handleSetProductAuction,
      togglingAvailabilityProductId,
      togglingAuctionProductId,
      isPremiumUser,
      loyaltyPoints,
      loyaltyPointsReserved,
      setIsLoginModalOpen,
      catalogSentinelRef,
      catalogHasMore,
      isCatalogLoadingMore,
      catalogLoadMoreError,
      handleRetryCatalogLoadMore,
      myProductsModerationFilter,
      catalogFollowingOnly,
      catalogAuctionOnly,
      catalogInstallmentOnly,
      catalogSaleOnly,
      catalogAllCities,
      catalogSort,
      catalogCityFilterLabel,
      handleShowAllCatalogCities,
      authUser,
      sellerRaffleActive,
      raffleParticipationPendingProductId,
      homeCuratedProductLists,
      showCuratedProductLists,
      isCuratedProductListsLoading,
    ],
  );
};
