import { INSTALLMENT_UI } from "../../../shared/config/appUiCopy.js";
import {
  INSTALLMENT_CONTRACT_STATUS_CANCELLED,
  INSTALLMENT_CONTRACT_STATUS_COMPLETED,
  INSTALLMENT_CONTRACT_STATUS_DEFAULTED,
  INSTALLMENT_SALES_LIST_FILTER_IN_PROGRESS,
} from "../model/constants.js";

/** @type {Array<{ value: string; label: string }>} */
export const INSTALLMENT_CONTRACT_STATUS_FILTER_OPTIONS = [
  { value: "", label: INSTALLMENT_UI.CONTRACT_STATUS_FILTER_ALL },
  {
    value: INSTALLMENT_SALES_LIST_FILTER_IN_PROGRESS,
    label: INSTALLMENT_UI.CONTRACT_STATUS_FILTER_IN_PROGRESS,
  },
  {
    value: INSTALLMENT_CONTRACT_STATUS_COMPLETED,
    label: INSTALLMENT_UI.CONTRACT_STATUS_FILTER_COMPLETED,
  },
  {
    value: INSTALLMENT_CONTRACT_STATUS_DEFAULTED,
    label: INSTALLMENT_UI.CONTRACT_STATUS_FILTER_DEFAULTED,
  },
  {
    value: INSTALLMENT_CONTRACT_STATUS_CANCELLED,
    label: INSTALLMENT_UI.CONTRACT_STATUS_FILTER_CANCELLED,
  },
];
