import {
  PRODUCT_GRID_COLUMNS_COMPACT,
  PRODUCT_GRID_COLUMNS_MEDIUM,
  PRODUCT_GRID_COLUMNS_WIDE,
  PRODUCT_GRID_GAP,
  SCREEN_LARGE_TABLET_MIN_WIDTH,
  SCREEN_MEDIUM_TABLET_MIN_WIDTH,
  SCREEN_NARROW_MAX_WIDTH,
  SCREEN_PRODUCT_GRID_2_COL_MAX_WIDTH,
  SCREEN_PRODUCT_GRID_4_COL_MIN_WIDTH,
  SCREEN_SMALL_TABLET_MIN_WIDTH,
  resolveProductGridColumns,
} from "@/shared/lib/screenBreakpoints";
import { SCREEN_CONTENT_PADDING_HORIZONTAL } from "@/shared/theme/screenContentLayout";

export const CATALOG_BROWSER_GRID_GAP = PRODUCT_GRID_GAP;
export const CATALOG_BROWSER_PAGE_PADDING = SCREEN_CONTENT_PADDING_HORIZONTAL;
export const CATALOG_BROWSER_GRID_NARROW_MAX_WIDTH = SCREEN_NARROW_MAX_WIDTH;
export const CATALOG_BROWSER_GRID_TABLET_MIN_WIDTH = SCREEN_SMALL_TABLET_MIN_WIDTH;
export const CATALOG_BROWSER_GRID_MEDIUM_TABLET_MIN_WIDTH = SCREEN_MEDIUM_TABLET_MIN_WIDTH;
export const CATALOG_BROWSER_GRID_LARGE_TABLET_MIN_WIDTH = SCREEN_LARGE_TABLET_MIN_WIDTH;
export const CATALOG_BROWSER_GRID_3_COL_MIN_WIDTH = SCREEN_PRODUCT_GRID_2_COL_MAX_WIDTH + 1;
export const CATALOG_BROWSER_GRID_4_COL_MIN_WIDTH = SCREEN_PRODUCT_GRID_4_COL_MIN_WIDTH;
export const CATALOG_BROWSER_GRID_COLUMNS_NARROW = PRODUCT_GRID_COLUMNS_COMPACT;
export const CATALOG_BROWSER_GRID_COLUMNS_DEFAULT = PRODUCT_GRID_COLUMNS_MEDIUM;
export const CATALOG_BROWSER_GRID_COLUMNS_TABLET = PRODUCT_GRID_COLUMNS_MEDIUM;
export const CATALOG_BROWSER_GRID_COLUMNS_MEDIUM_TABLET = PRODUCT_GRID_COLUMNS_MEDIUM;
export const CATALOG_BROWSER_GRID_COLUMNS_LARGE_TABLET = PRODUCT_GRID_COLUMNS_WIDE;

/** @deprecated используйте resolveCatalogBrowserGridColumns */
export const CATALOG_BROWSER_GRID_COLUMNS = CATALOG_BROWSER_GRID_COLUMNS_DEFAULT;

export const resolveCatalogBrowserGridColumns = (screenWidth: number, screenHeight?: number) =>
  resolveProductGridColumns({
    width: screenWidth,
    height: screenHeight ?? screenWidth,
  });
