/** Паритет `SellerProductsPage.css` + `SellerProfileQuickStats.css`. */
export const SELLER_PRODUCTS_PAGE_LAYOUT = {
  screenPaddingTop: 12,
  screenGap: 8,
  navMinHeight: 44,
  navBackSize: 40,
  navTitleFontSize: 17,
  navTitleLineHeight: 21,
  metaZonePaddingVertical: 12,
  metaZonePaddingHorizontal: 14,
  metaZoneBorderRadius: 20,
  metaZoneGap: 8,
  metaActionsGap: 4,
  sellerNameFontSize: 16,
  sellerNameLineHeight: 21,
  sellerNameFontWeight: "600" as const,
  shareMetaSize: 34,
  shareMetaIconSize: 20,
  followPaddingVertical: 8,
  followPaddingHorizontal: 14,
  followBorderRadius: 10,
  followFontSize: 14,
  statsGridGap: 8,
  statsItemPaddingVertical: 12,
  statsItemPaddingHorizontal: 14,
  statsItemBorderRadius: 20,
  statsValueFontSize: 15,
  statsPhoneValueFontSize: 13,
  statsLabelFontSize: 11,
  statsStackBreakpoint: 420,
  statsColumnFlexFollowers: 0.78,
  statsColumnFlexRating: 0.78,
  statsColumnFlexPhone: 1.44,
  shelfRowGap: 7,
  shelfRowPaddingTop: 2,
  shelfRowPaddingBottom: 4,
  shelfChipPaddingVertical: 6,
  shelfChipPaddingHorizontal: 14,
  shelfChipFontSize: 14,
} as const;
