import { createAsyncRouter } from "../utils/createAsyncRouter.js";
import {
  postProductController,
  getProductsController,
  getMyProductsController,
  getProductCategoryDisplaysController,
  patchProductCategoryDisplayController,
  patchProductCategoryNodeDisplayController,
  getProductCategoryRootsController,
  getProductCategorySearchController,
  getProductCategoryChildrenController,
  getProductCategoryBreadcrumbController,
  listProductCategoriesAdminController,
  createProductCategoryAdminController,
  patchProductCategoryAdminController,
  deleteProductCategoryAdminController,
  listProductSearchSynonymsAdminController,
  createProductSearchSynonymAdminController,
  patchProductSearchSynonymAdminController,
  deleteProductSearchSynonymAdminController,
  getHomeCuratedProductListsController,
  listCuratedProductListsAdminController,
  previewCuratedListProductAdminController,
  createCuratedProductListAdminController,
  reorderCuratedProductListsAdminController,
  patchCuratedProductListAdminController,
  deleteCuratedProductListAdminController,
  addCuratedProductListItemAdminController,
  removeCuratedProductListItemAdminController,
  getHomeCuratedCategoryListsController,
  listCuratedCategoryListsAdminController,
  previewCuratedCategoryListItemAdminController,
  createCuratedCategoryListAdminController,
  reorderCuratedCategoryListsAdminController,
  patchCuratedCategoryListAdminController,
  deleteCuratedCategoryListAdminController,
  addCuratedCategoryListItemAdminController,
  removeCuratedCategoryListItemAdminController,
  getProductCatalogFeedTileDisplaysController,
  patchProductCatalogFeedTileDisplayController,
  getProductManageToggleDisplaysController,
  patchProductManageToggleDisplayController,
  getProductBadgeExplainsController,
  patchProductBadgeExplainController,
  getCatalogProductByIdController,
  getComparableProductsController,
  deleteMyProductController,
  patchMyProductController,
  recordProductViewController,
  getPendingModerationProductsController,
  getPendingModerationProductsCountController,
  approveProductModerationController,
  rejectProductModerationController,
  submitProductReportController,
  getMyProductReportStatusController,
  getPendingProductReportsController,
  getPendingProductReportsCountController,
  resolveProductReportsForProductController,
  submitProductPriceOfferController,
  patchMyProductPriceOfferController,
  cancelMyProductPriceOfferController,
  getMyProductPriceOfferController,
  getTopProductPriceOffersController,
  getSellerProductPriceOffersController,
  acceptProductPriceOfferController,
  rejectProductPriceOfferController,
  getSellerProductPriceOfferArchiveController,
  listProductReviewsController,
  getProductReviewSummaryController,
  submitProductReviewController,
  patchMyProductReviewController,
  deleteMyProductReviewController,
  listProductQuestionsController,
  getProductQuestionSummaryController,
  askProductQuestionController,
  answerProductQuestionController,
  hideProductQuestionController,
  deleteMyProductQuestionController,
  getProductPromotionTariffsController,
  requestProductPromotionController,
  getMyProductPromotionsController,
  getPendingProductPromotionsController,
  getPendingProductPromotionsCountController,
  approveProductPromotionController,
  rejectProductPromotionController,
  listProductPromoCodesController,
  replaceProductPromoCodesController,
  activateProductPromoCodeController,
  listMyAppliedProductPromosController,
  getFeaturedRaffleController,
  getRaffleByIdController,
  getRaffleProductsController,
  createRaffleController,
  getMyRaffleController,
  getRaffleCreateAdvertisingController,
  unlockRaffleCreateController,
  cancelRaffleCreateController,
  patchMyRaffleController,
  patchRaffleByStaffController,
  deleteMyRaffleController,
  deleteRaffleByStaffController,
  pauseMyRaffleController,
  setProductRaffleParticipationController,
  getPendingRafflesController,
  getPendingRafflesCountController,
  approveRaffleController,
  rejectRaffleController,
  getProductInstallmentProgramController,
  upsertProductInstallmentProgramController,
  createInstallmentContractController,
  downloadProductBulkImportTemplateController,
  getProductBulkImportJobStatusController,
  submitProductBulkImportController,
} from "../controllers/index.js";
import {
  checkAuthMW,
  checkOptionalAuthMW,
  checkAdminMW,
  checkProductModeratorMW,
  productReportRateLimiter,
  productPriceOfferRateLimiter,
  productReviewRateLimiter,
  productQuestionRateLimiter,
  productCompareRateLimiter,
  productCreateRateLimiter,
  productBulkImportRateLimiter,
  catalogListRateLimiter,
  moneyMutationRateLimiter,
  installmentActionRateLimiter,
} from "../middlewares/index.js";
import { uploadExcelMW } from "../middlewares/uploadExcelMW.js";
import {
  makeProductValidation,
  productIdParamValidation,
  productsSearchValidation,
  patchMyProductValidation,
  rejectProductModerationValidation,
  submitProductReportValidation,
  resolveProductReportsValidation,
  submitProductPriceOfferValidation,
  patchProductPriceOfferValidation,
  productPriceOfferIdParamValidation,
  submitProductReviewValidation,
  patchProductReviewValidation,
  productReviewsListValidation,
  askProductQuestionValidation,
  answerProductQuestionValidation,
  productQuestionsListValidation,
  productQuestionIdParamValidation,
  requestProductPromotionValidation,
  myProductPromotionsValidation,
  promotionIdParamValidation,
  rejectProductPromotionValidation,
  replaceProductPromoCodesValidation,
  activateProductPromoCodeValidation,
  createRaffleValidation,
  patchRaffleValidation,
  raffleIdParamValidation,
  rejectRaffleValidation,
  raffleProductsValidation,
  setProductRaffleParticipationValidation,
  productCategoryIdParamValidation,
  createProductCategoryAdminValidation,
  deleteProductCategoryAdminValidation,
  patchProductCategoryAdminValidation,
  productSearchSynonymIdParamValidation,
  createProductSearchSynonymValidation,
  patchProductSearchSynonymValidation,
  curatedProductListIdParamValidation,
  curatedProductListProductIdParamValidation,
  curatedProductPreviewParamValidation,
  createCuratedProductListValidation,
  patchCuratedProductListValidation,
  reorderCuratedProductListsValidation,
  addCuratedProductListItemValidation,
  curatedCategoryListIdParamValidation,
  curatedCategoryListItemParamValidation,
  curatedCategoryItemPreviewQueryValidation,
  createCuratedCategoryListValidation,
  patchCuratedCategoryListValidation,
  reorderCuratedCategoryListsValidation,
  addCuratedCategoryListItemValidation,
  patchProductCategoryDisplayValidation,
  patchProductCategoryNodeDisplayValidation,
  catalogFeedTileKeyParamValidation,
  patchProductCatalogFeedTileDisplayValidation,
  productManageToggleKeyParamValidation,
  patchProductManageToggleDisplayValidation,
  productBadgeExplainKeyParamValidation,
  patchProductBadgeExplainValidation,
  upsertProductInstallmentProgramValidation,
  createInstallmentContractValidation,
  productBulkImportJobIdParamValidation,
} from "../validations/index.js";

const router = createAsyncRouter();

router.post(
  "/",
  checkAuthMW,
  productCreateRateLimiter,
  makeProductValidation,
  postProductController,
);
router.get(
  "/bulk-import/template",
  checkAuthMW,
  downloadProductBulkImportTemplateController,
);
router.post(
  "/bulk-import",
  checkAuthMW,
  productBulkImportRateLimiter,
  uploadExcelMW.single("file"),
  submitProductBulkImportController,
);
router.get(
  "/bulk-import/:jobId",
  checkAuthMW,
  productBulkImportJobIdParamValidation,
  getProductBulkImportJobStatusController,
);
router.get(
  "/",
  catalogListRateLimiter,
  productsSearchValidation,
  checkOptionalAuthMW,
  getProductsController,
);
router.get("/category-displays", getProductCategoryDisplaysController);
router.get("/categories/roots", getProductCategoryRootsController);
router.get("/categories/search", getProductCategorySearchController);
router.get(
  "/categories/:categoryId/children",
  productCategoryIdParamValidation,
  getProductCategoryChildrenController,
);
router.get(
  "/categories/:categoryId/breadcrumb",
  productCategoryIdParamValidation,
  getProductCategoryBreadcrumbController,
);
router.get(
  "/admin/search-synonyms",
  checkAuthMW,
  checkAdminMW,
  listProductSearchSynonymsAdminController,
);
router.post(
  "/admin/search-synonyms",
  checkAuthMW,
  checkAdminMW,
  createProductSearchSynonymValidation,
  createProductSearchSynonymAdminController,
);
router.patch(
  "/admin/search-synonyms/:synonymId",
  checkAuthMW,
  checkAdminMW,
  productSearchSynonymIdParamValidation,
  patchProductSearchSynonymValidation,
  patchProductSearchSynonymAdminController,
);
router.delete(
  "/admin/search-synonyms/:synonymId",
  checkAuthMW,
  checkAdminMW,
  productSearchSynonymIdParamValidation,
  deleteProductSearchSynonymAdminController,
);
router.get(
  "/curated-lists/home",
  checkOptionalAuthMW,
  getHomeCuratedProductListsController,
);
router.get(
  "/admin/curated-lists",
  checkAuthMW,
  checkAdminMW,
  listCuratedProductListsAdminController,
);
router.get(
  "/admin/curated-lists/product-preview/:productId",
  checkAuthMW,
  checkAdminMW,
  curatedProductPreviewParamValidation,
  previewCuratedListProductAdminController,
);
router.post(
  "/admin/curated-lists",
  checkAuthMW,
  checkAdminMW,
  createCuratedProductListValidation,
  createCuratedProductListAdminController,
);
router.patch(
  "/admin/curated-lists/reorder",
  checkAuthMW,
  checkAdminMW,
  reorderCuratedProductListsValidation,
  reorderCuratedProductListsAdminController,
);
router.patch(
  "/admin/curated-lists/:listId",
  checkAuthMW,
  checkAdminMW,
  patchCuratedProductListValidation,
  patchCuratedProductListAdminController,
);
router.delete(
  "/admin/curated-lists/:listId",
  checkAuthMW,
  checkAdminMW,
  curatedProductListIdParamValidation,
  deleteCuratedProductListAdminController,
);
router.post(
  "/admin/curated-lists/:listId/products",
  checkAuthMW,
  checkAdminMW,
  addCuratedProductListItemValidation,
  addCuratedProductListItemAdminController,
);
router.delete(
  "/admin/curated-lists/:listId/products/:productId",
  checkAuthMW,
  checkAdminMW,
  curatedProductListProductIdParamValidation,
  removeCuratedProductListItemAdminController,
);
router.get(
  "/curated-category-lists/home",
  checkOptionalAuthMW,
  getHomeCuratedCategoryListsController,
);
router.get(
  "/admin/curated-category-lists",
  checkAuthMW,
  checkAdminMW,
  listCuratedCategoryListsAdminController,
);
router.get(
  "/admin/curated-category-lists/item-preview",
  checkAuthMW,
  checkAdminMW,
  curatedCategoryItemPreviewQueryValidation,
  previewCuratedCategoryListItemAdminController,
);
router.post(
  "/admin/curated-category-lists",
  checkAuthMW,
  checkAdminMW,
  createCuratedCategoryListValidation,
  createCuratedCategoryListAdminController,
);
router.patch(
  "/admin/curated-category-lists/reorder",
  checkAuthMW,
  checkAdminMW,
  reorderCuratedCategoryListsValidation,
  reorderCuratedCategoryListsAdminController,
);
router.patch(
  "/admin/curated-category-lists/:listId",
  checkAuthMW,
  checkAdminMW,
  patchCuratedCategoryListValidation,
  patchCuratedCategoryListAdminController,
);
router.delete(
  "/admin/curated-category-lists/:listId",
  checkAuthMW,
  checkAdminMW,
  curatedCategoryListIdParamValidation,
  deleteCuratedCategoryListAdminController,
);
router.post(
  "/admin/curated-category-lists/:listId/items",
  checkAuthMW,
  checkAdminMW,
  addCuratedCategoryListItemValidation,
  addCuratedCategoryListItemAdminController,
);
router.delete(
  "/admin/curated-category-lists/:listId/items/:itemKey",
  checkAuthMW,
  checkAdminMW,
  curatedCategoryListItemParamValidation,
  removeCuratedCategoryListItemAdminController,
);
router.get(
  "/admin/categories",
  checkAuthMW,
  checkAdminMW,
  listProductCategoriesAdminController,
);
router.post(
  "/admin/categories",
  checkAuthMW,
  checkAdminMW,
  createProductCategoryAdminValidation,
  createProductCategoryAdminController,
);
router.patch(
  "/admin/categories/:categoryId",
  checkAuthMW,
  checkAdminMW,
  productCategoryIdParamValidation,
  patchProductCategoryAdminValidation,
  patchProductCategoryAdminController,
);
router.delete(
  "/admin/categories/:categoryId",
  checkAuthMW,
  checkAdminMW,
  productCategoryIdParamValidation,
  deleteProductCategoryAdminValidation,
  deleteProductCategoryAdminController,
);
router.patch(
  "/category-displays/:categorySlug",
  checkAuthMW,
  checkAdminMW,
  patchProductCategoryDisplayValidation,
  patchProductCategoryDisplayController,
);
router.patch(
  "/category-node-displays/:categoryId",
  checkAuthMW,
  checkAdminMW,
  patchProductCategoryNodeDisplayValidation,
  patchProductCategoryNodeDisplayController,
);
router.get("/catalog-feed-displays", getProductCatalogFeedTileDisplaysController);
router.patch(
  "/catalog-feed-displays/:tileKey",
  checkAuthMW,
  checkAdminMW,
  catalogFeedTileKeyParamValidation,
  patchProductCatalogFeedTileDisplayValidation,
  patchProductCatalogFeedTileDisplayController,
);
router.get("/manage-toggle-displays", getProductManageToggleDisplaysController);
router.patch(
  "/manage-toggle-displays/:toggleKey",
  checkAuthMW,
  checkProductModeratorMW,
  productManageToggleKeyParamValidation,
  patchProductManageToggleDisplayValidation,
  patchProductManageToggleDisplayController,
);
router.get("/badge-explains", getProductBadgeExplainsController);
router.patch(
  "/badge-explains/:badgeKey",
  checkAuthMW,
  checkProductModeratorMW,
  productBadgeExplainKeyParamValidation,
  patchProductBadgeExplainValidation,
  patchProductBadgeExplainController,
);
router.get("/my", checkAuthMW, productsSearchValidation, getMyProductsController);
router.get("/raffles/featured", getFeaturedRaffleController);
router.get("/raffles/my", checkAuthMW, getMyRaffleController);
router.get(
  "/raffles/create-advertising",
  checkAuthMW,
  getRaffleCreateAdvertisingController,
);
router.post(
  "/raffles/unlock-create",
  checkAuthMW,
  moneyMutationRateLimiter,
  unlockRaffleCreateController,
);
router.post("/raffles/cancel-create", checkAuthMW, cancelRaffleCreateController);
router.get(
  "/raffles/pending/count",
  checkAuthMW,
  checkProductModeratorMW,
  getPendingRafflesCountController,
);
router.get(
  "/raffles/pending",
  checkAuthMW,
  checkProductModeratorMW,
  getPendingRafflesController,
);
router.post("/raffles", checkAuthMW, createRaffleValidation, createRaffleController);
router.get(
  "/raffles/:raffleId/products",
  raffleProductsValidation,
  getRaffleProductsController,
);
router.get("/raffles/:raffleId", raffleIdParamValidation, getRaffleByIdController);
router.delete(
  "/raffles/my/:raffleId",
  checkAuthMW,
  raffleIdParamValidation,
  deleteMyRaffleController,
);
router.patch(
  "/raffles/:raffleId",
  checkAuthMW,
  patchRaffleValidation,
  patchMyRaffleController,
);
router.patch(
  "/raffles/:raffleId/staff",
  checkAuthMW,
  checkProductModeratorMW,
  patchRaffleValidation,
  patchRaffleByStaffController,
);
router.delete(
  "/raffles/:raffleId",
  checkAuthMW,
  checkProductModeratorMW,
  raffleIdParamValidation,
  deleteRaffleByStaffController,
);
router.patch(
  "/raffles/:raffleId/pause",
  checkAuthMW,
  raffleIdParamValidation,
  pauseMyRaffleController,
);
router.patch(
  "/raffles/:raffleId/approve",
  checkAuthMW,
  checkProductModeratorMW,
  raffleIdParamValidation,
  approveRaffleController,
);
router.patch(
  "/raffles/:raffleId/reject",
  checkAuthMW,
  checkProductModeratorMW,
  rejectRaffleValidation,
  rejectRaffleController,
);
router.patch(
  "/:productId/raffle-participation",
  checkAuthMW,
  setProductRaffleParticipationValidation,
  setProductRaffleParticipationController,
);
router.get("/promotions/tariffs", getProductPromotionTariffsController);
router.get(
  "/promotions/pending/count",
  checkAuthMW,
  checkProductModeratorMW,
  getPendingProductPromotionsCountController,
);
router.get(
  "/promotions/pending",
  checkAuthMW,
  checkProductModeratorMW,
  getPendingProductPromotionsController,
);
router.patch(
  "/promotions/:promotionId/approve",
  checkAuthMW,
  checkProductModeratorMW,
  promotionIdParamValidation,
  approveProductPromotionController,
);
router.patch(
  "/promotions/:promotionId/reject",
  checkAuthMW,
  checkProductModeratorMW,
  rejectProductPromotionValidation,
  rejectProductPromotionController,
);
router.get(
  "/promotions/my",
  checkAuthMW,
  myProductPromotionsValidation,
  getMyProductPromotionsController,
);
router.post(
  "/:productId/promotions/request",
  checkAuthMW,
  moneyMutationRateLimiter,
  productIdParamValidation,
  requestProductPromotionValidation,
  requestProductPromotionController,
);
router.get(
  "/promo-activations/me",
  checkAuthMW,
  listMyAppliedProductPromosController,
);
router.get(
  "/:productId/promo-codes",
  checkAuthMW,
  productIdParamValidation,
  listProductPromoCodesController,
);
router.put(
  "/:productId/promo-codes",
  checkAuthMW,
  productIdParamValidation,
  replaceProductPromoCodesValidation,
  replaceProductPromoCodesController,
);
router.post(
  "/:productId/promo-codes/activate",
  checkAuthMW,
  productIdParamValidation,
  activateProductPromoCodeValidation,
  activateProductPromoCodeController,
);
router.get(
  "/moderation/pending/count",
  checkAuthMW,
  checkProductModeratorMW,
  getPendingModerationProductsCountController,
);
router.get(
  "/moderation/pending",
  checkAuthMW,
  checkProductModeratorMW,
  productsSearchValidation,
  getPendingModerationProductsController,
);
router.get(
  "/reports/pending/count",
  checkAuthMW,
  checkProductModeratorMW,
  getPendingProductReportsCountController,
);
router.get(
  "/reports/pending",
  checkAuthMW,
  checkProductModeratorMW,
  getPendingProductReportsController,
);
router.patch(
  "/reports/product/:productId/resolve",
  checkAuthMW,
  checkProductModeratorMW,
  productIdParamValidation,
  resolveProductReportsValidation,
  resolveProductReportsForProductController,
);
router.get(
  "/:productId/installment-program",
  checkOptionalAuthMW,
  productIdParamValidation,
  getProductInstallmentProgramController,
);
router.put(
  "/:productId/installment-program",
  checkAuthMW,
  productIdParamValidation,
  upsertProductInstallmentProgramValidation,
  upsertProductInstallmentProgramController,
);
router.post(
  "/:productId/installment-contracts",
  checkAuthMW,
  installmentActionRateLimiter,
  productIdParamValidation,
  createInstallmentContractValidation,
  createInstallmentContractController,
);
router.get(
  "/:productId/price-offers/top",
  productIdParamValidation,
  getTopProductPriceOffersController,
);
router.get(
  "/:productId/price-offers/me",
  checkAuthMW,
  productIdParamValidation,
  getMyProductPriceOfferController,
);
router.get(
  "/:productId/price-offers/archive",
  checkAuthMW,
  productIdParamValidation,
  getSellerProductPriceOfferArchiveController,
);
router.get(
  "/:productId/price-offers",
  checkAuthMW,
  productIdParamValidation,
  getSellerProductPriceOffersController,
);
router.post(
  "/:productId/price-offers",
  checkAuthMW,
  productPriceOfferRateLimiter,
  productIdParamValidation,
  submitProductPriceOfferValidation,
  submitProductPriceOfferController,
);
router.patch(
  "/:productId/price-offers/me",
  checkAuthMW,
  productPriceOfferRateLimiter,
  productIdParamValidation,
  patchProductPriceOfferValidation,
  patchMyProductPriceOfferController,
);
router.delete(
  "/:productId/price-offers/me",
  checkAuthMW,
  productIdParamValidation,
  cancelMyProductPriceOfferController,
);
router.patch(
  "/:productId/price-offers/:offerId/accept",
  checkAuthMW,
  productIdParamValidation,
  productPriceOfferIdParamValidation,
  acceptProductPriceOfferController,
);
router.patch(
  "/:productId/price-offers/:offerId/reject",
  checkAuthMW,
  productIdParamValidation,
  productPriceOfferIdParamValidation,
  rejectProductPriceOfferController,
);
router.get(
  "/:productId/catalog",
  productIdParamValidation,
  checkOptionalAuthMW,
  getCatalogProductByIdController,
);
router.get(
  "/:productId/compare",
  productCompareRateLimiter,
  productIdParamValidation,
  getComparableProductsController,
);
router.get(
  "/:productId/reviews/summary",
  productIdParamValidation,
  checkOptionalAuthMW,
  getProductReviewSummaryController,
);
router.get(
  "/:productId/reviews",
  productIdParamValidation,
  productReviewsListValidation,
  listProductReviewsController,
);
router.post(
  "/:productId/reviews",
  checkAuthMW,
  productReviewRateLimiter,
  productIdParamValidation,
  submitProductReviewValidation,
  submitProductReviewController,
);
router.patch(
  "/:productId/reviews/me",
  checkAuthMW,
  productReviewRateLimiter,
  productIdParamValidation,
  patchProductReviewValidation,
  patchMyProductReviewController,
);
router.delete(
  "/:productId/reviews/me",
  checkAuthMW,
  productIdParamValidation,
  deleteMyProductReviewController,
);
router.get(
  "/:productId/questions/summary",
  productIdParamValidation,
  checkOptionalAuthMW,
  getProductQuestionSummaryController,
);
router.get(
  "/:productId/questions",
  productIdParamValidation,
  productQuestionsListValidation,
  checkOptionalAuthMW,
  listProductQuestionsController,
);
router.post(
  "/:productId/questions",
  checkAuthMW,
  productQuestionRateLimiter,
  productIdParamValidation,
  askProductQuestionValidation,
  askProductQuestionController,
);
router.put(
  "/:productId/questions/:questionId/answer",
  checkAuthMW,
  productQuestionIdParamValidation,
  answerProductQuestionValidation,
  answerProductQuestionController,
);
router.patch(
  "/:productId/questions/:questionId/hide",
  checkAuthMW,
  productQuestionIdParamValidation,
  hideProductQuestionController,
);
router.delete(
  "/:productId/questions/:questionId",
  checkAuthMW,
  productQuestionIdParamValidation,
  deleteMyProductQuestionController,
);
router.get(
  "/:productId/report/me",
  checkAuthMW,
  productIdParamValidation,
  getMyProductReportStatusController,
);
router.post(
  "/:productId/report",
  checkAuthMW,
  productReportRateLimiter,
  productIdParamValidation,
  submitProductReportValidation,
  submitProductReportController,
);
router.post(
  "/:productId/view",
  checkAuthMW,
  productIdParamValidation,
  recordProductViewController,
);
router.patch(
  "/:productId/moderation/approve",
  checkAuthMW,
  checkProductModeratorMW,
  productIdParamValidation,
  approveProductModerationController,
);
router.patch(
  "/:productId/moderation/reject",
  checkAuthMW,
  checkProductModeratorMW,
  productIdParamValidation,
  rejectProductModerationValidation,
  rejectProductModerationController,
);
router.patch(
  "/:productId",
  checkAuthMW,
  productIdParamValidation,
  patchMyProductValidation,
  patchMyProductController,
);
router.delete(
  "/:productId",
  checkAuthMW,
  productIdParamValidation,
  deleteMyProductController,
);

export { router as productRouter };
