import { Router } from 'express';
import {
    postProductController,
    getProductsController,
    getMyProductsController,
    getCatalogProductByIdController,
    deleteMyProductController,
    patchMyProductController,
    recordProductViewController,
    getPendingModerationProductsController,
    approveProductModerationController,
    rejectProductModerationController,
    submitProductReportController,
    getMyProductReportStatusController,
    getPendingProductReportsController,
    getPendingProductReportsCountController,
    resolveProductReportsForProductController,
    submitProductPriceOfferController,
    patchMyProductPriceOfferController,
    cancelMyProductPriceOfferController,
    getMyProductPriceOfferController,
    getTopProductPriceOffersController,
    getSellerProductPriceOffersController,
    acceptProductPriceOfferController,
    rejectProductPriceOfferController,
    getSellerProductPriceOfferArchiveController,
    listProductReviewsController,
    getProductReviewSummaryController,
    submitProductReviewController,
    patchMyProductReviewController,
    deleteMyProductReviewController,
} from '../controllers/index.js';
import {
    checkAuthMW,
    checkOptionalAuthMW,
    checkProductModeratorMW,
    productReportRateLimiter,
    productPriceOfferRateLimiter,
    productReviewRateLimiter,
} from '../middlewares/index.js';
import {
    makeProductValidation,
    productIdParamValidation,
    productsSearchValidation,
    patchMyProductValidation,
    rejectProductModerationValidation,
    submitProductReportValidation,
    resolveProductReportsValidation,
    submitProductPriceOfferValidation,
    patchProductPriceOfferValidation,
    productPriceOfferIdParamValidation,
    submitProductReviewValidation,
    patchProductReviewValidation,
    productReviewsListValidation,
} from '../validations/index.js';

const router = Router();

router.post('/', checkAuthMW, makeProductValidation, postProductController);
router.get('/', productsSearchValidation, checkOptionalAuthMW, getProductsController);
router.get('/my', checkAuthMW, productsSearchValidation, getMyProductsController);
router.get(
    '/moderation/pending',
    checkAuthMW,
    checkProductModeratorMW,
    productsSearchValidation,
    getPendingModerationProductsController,
);
router.get(
    '/reports/pending/count',
    checkAuthMW,
    checkProductModeratorMW,
    getPendingProductReportsCountController,
);
router.get(
    '/reports/pending',
    checkAuthMW,
    checkProductModeratorMW,
    getPendingProductReportsController,
);
router.patch(
    '/reports/product/:productId/resolve',
    checkAuthMW,
    checkProductModeratorMW,
    productIdParamValidation,
    resolveProductReportsValidation,
    resolveProductReportsForProductController,
);
router.get(
    '/:productId/price-offers/top',
    productIdParamValidation,
    getTopProductPriceOffersController,
);
router.get(
    '/:productId/price-offers/me',
    checkAuthMW,
    productIdParamValidation,
    getMyProductPriceOfferController,
);
router.get(
    '/:productId/price-offers/archive',
    checkAuthMW,
    productIdParamValidation,
    getSellerProductPriceOfferArchiveController,
);
router.get(
    '/:productId/price-offers',
    checkAuthMW,
    productIdParamValidation,
    getSellerProductPriceOffersController,
);
router.post(
    '/:productId/price-offers',
    checkAuthMW,
    productPriceOfferRateLimiter,
    productIdParamValidation,
    submitProductPriceOfferValidation,
    submitProductPriceOfferController,
);
router.patch(
    '/:productId/price-offers/me',
    checkAuthMW,
    productPriceOfferRateLimiter,
    productIdParamValidation,
    patchProductPriceOfferValidation,
    patchMyProductPriceOfferController,
);
router.delete(
    '/:productId/price-offers/me',
    checkAuthMW,
    productIdParamValidation,
    cancelMyProductPriceOfferController,
);
router.patch(
    '/:productId/price-offers/:offerId/accept',
    checkAuthMW,
    productIdParamValidation,
    productPriceOfferIdParamValidation,
    acceptProductPriceOfferController,
);
router.patch(
    '/:productId/price-offers/:offerId/reject',
    checkAuthMW,
    productIdParamValidation,
    productPriceOfferIdParamValidation,
    rejectProductPriceOfferController,
);
router.get(
    '/:productId/catalog',
    productIdParamValidation,
    checkOptionalAuthMW,
    getCatalogProductByIdController,
);
router.get(
    '/:productId/reviews/summary',
    productIdParamValidation,
    checkOptionalAuthMW,
    getProductReviewSummaryController,
);
router.get(
    '/:productId/reviews',
    productIdParamValidation,
    productReviewsListValidation,
    listProductReviewsController,
);
router.post(
    '/:productId/reviews',
    checkAuthMW,
    productReviewRateLimiter,
    productIdParamValidation,
    submitProductReviewValidation,
    submitProductReviewController,
);
router.patch(
    '/:productId/reviews/me',
    checkAuthMW,
    productReviewRateLimiter,
    productIdParamValidation,
    patchProductReviewValidation,
    patchMyProductReviewController,
);
router.delete(
    '/:productId/reviews/me',
    checkAuthMW,
    productIdParamValidation,
    deleteMyProductReviewController,
);
router.get(
    '/:productId/report/me',
    checkAuthMW,
    productIdParamValidation,
    getMyProductReportStatusController,
);
router.post(
    '/:productId/report',
    checkAuthMW,
    productReportRateLimiter,
    productIdParamValidation,
    submitProductReportValidation,
    submitProductReportController,
);
router.post(
    '/:productId/view',
    checkAuthMW,
    productIdParamValidation,
    recordProductViewController,
);
router.patch(
    '/:productId/moderation/approve',
    checkAuthMW,
    checkProductModeratorMW,
    productIdParamValidation,
    approveProductModerationController,
);
router.patch(
    '/:productId/moderation/reject',
    checkAuthMW,
    checkProductModeratorMW,
    productIdParamValidation,
    rejectProductModerationValidation,
    rejectProductModerationController,
);
router.patch(
    '/:productId',
    checkAuthMW,
    productIdParamValidation,
    patchMyProductValidation,
    patchMyProductController,
);
router.delete(
    '/:productId',
    checkAuthMW,
    productIdParamValidation,
    deleteMyProductController,
);

export { router as productRouter };
