import { Router } from 'express';
import {
    postProductController,
    getProductsController,
    getMyProductsController,
    getCatalogProductByIdController,
    deleteMyProductController,
    patchMyProductController,
    recordProductViewController,
    getPendingModerationProductsController,
    getPendingModerationProductsCountController,
    approveProductModerationController,
    rejectProductModerationController,
    submitProductReportController,
    getMyProductReportStatusController,
    getPendingProductReportsController,
    getPendingProductReportsCountController,
    resolveProductReportsForProductController,
    submitProductPriceOfferController,
    patchMyProductPriceOfferController,
    cancelMyProductPriceOfferController,
    getMyProductPriceOfferController,
    getTopProductPriceOffersController,
    getSellerProductPriceOffersController,
    acceptProductPriceOfferController,
    rejectProductPriceOfferController,
    getSellerProductPriceOfferArchiveController,
    listProductReviewsController,
    getProductReviewSummaryController,
    submitProductReviewController,
    patchMyProductReviewController,
    deleteMyProductReviewController,
    getProductPromotionTariffsController,
    requestProductPromotionController,
    getMyProductPromotionsController,
    getPendingProductPromotionsController,
    getPendingProductPromotionsCountController,
    approveProductPromotionController,
    rejectProductPromotionController,
    cancelProductPromotionByStaffController,
    extendProductPromotionByStaffController,
    getFeaturedRaffleController,
    getRaffleByIdController,
    getRaffleProductsController,
    createRaffleController,
    getMyRaffleController,
    patchMyRaffleController,
    patchRaffleByStaffController,
    deleteMyRaffleController,
    deleteRaffleByStaffController,
    pauseMyRaffleController,
    setProductRaffleParticipationController,
    getPendingRafflesController,
    getPendingRafflesCountController,
    approveRaffleController,
    rejectRaffleController,
} from '../controllers/index.js';
import {
    checkAuthMW,
    checkOptionalAuthMW,
    checkProductModeratorMW,
    productReportRateLimiter,
    productPriceOfferRateLimiter,
    productReviewRateLimiter,
} from '../middlewares/index.js';
import {
    makeProductValidation,
    productIdParamValidation,
    productsSearchValidation,
    patchMyProductValidation,
    rejectProductModerationValidation,
    submitProductReportValidation,
    resolveProductReportsValidation,
    submitProductPriceOfferValidation,
    patchProductPriceOfferValidation,
    productPriceOfferIdParamValidation,
    submitProductReviewValidation,
    patchProductReviewValidation,
    productReviewsListValidation,
    requestProductPromotionValidation,
    promotionIdParamValidation,
    myProductPromotionsValidation,
    createRaffleValidation,
    patchRaffleValidation,
    raffleIdParamValidation,
    rejectRaffleValidation,
    raffleProductsValidation,
    setProductRaffleParticipationValidation,
} from '../validations/index.js';

const router = Router();

router.post('/', checkAuthMW, makeProductValidation, postProductController);
router.get('/', productsSearchValidation, checkOptionalAuthMW, getProductsController);
router.get('/my', checkAuthMW, productsSearchValidation, getMyProductsController);
router.get('/raffles/featured', getFeaturedRaffleController);
router.get('/raffles/my', checkAuthMW, getMyRaffleController);
router.get(
    '/raffles/pending/count',
    checkAuthMW,
    checkProductModeratorMW,
    getPendingRafflesCountController,
);
router.get(
    '/raffles/pending',
    checkAuthMW,
    checkProductModeratorMW,
    getPendingRafflesController,
);
router.post('/raffles', checkAuthMW, createRaffleValidation, createRaffleController);
router.get(
    '/raffles/:raffleId/products',
    raffleProductsValidation,
    getRaffleProductsController,
);
router.get('/raffles/:raffleId', raffleIdParamValidation, getRaffleByIdController);
router.delete(
    '/raffles/my/:raffleId',
    checkAuthMW,
    raffleIdParamValidation,
    deleteMyRaffleController,
);
router.patch(
    '/raffles/:raffleId',
    checkAuthMW,
    patchRaffleValidation,
    patchMyRaffleController,
);
router.patch(
    '/raffles/:raffleId/staff',
    checkAuthMW,
    checkProductModeratorMW,
    patchRaffleValidation,
    patchRaffleByStaffController,
);
router.delete(
    '/raffles/:raffleId',
    checkAuthMW,
    checkProductModeratorMW,
    raffleIdParamValidation,
    deleteRaffleByStaffController,
);
router.patch(
    '/raffles/:raffleId/pause',
    checkAuthMW,
    raffleIdParamValidation,
    pauseMyRaffleController,
);
router.patch(
    '/raffles/:raffleId/approve',
    checkAuthMW,
    checkProductModeratorMW,
    raffleIdParamValidation,
    approveRaffleController,
);
router.patch(
    '/raffles/:raffleId/reject',
    checkAuthMW,
    checkProductModeratorMW,
    rejectRaffleValidation,
    rejectRaffleController,
);
router.patch(
    '/:productId/raffle-participation',
    checkAuthMW,
    setProductRaffleParticipationValidation,
    setProductRaffleParticipationController,
);
router.get('/promotions/tariffs', getProductPromotionTariffsController);
router.get(
    '/promotions/my',
    checkAuthMW,
    myProductPromotionsValidation,
    getMyProductPromotionsController,
);
router.get(
    '/promotions/pending/count',
    checkAuthMW,
    checkProductModeratorMW,
    getPendingProductPromotionsCountController,
);
router.get(
    '/promotions/pending',
    checkAuthMW,
    checkProductModeratorMW,
    getPendingProductPromotionsController,
);
router.patch(
    '/promotions/:promotionId/approve',
    checkAuthMW,
    checkProductModeratorMW,
    promotionIdParamValidation,
    approveProductPromotionController,
);
router.patch(
    '/promotions/:promotionId/reject',
    checkAuthMW,
    checkProductModeratorMW,
    promotionIdParamValidation,
    rejectProductPromotionController,
);
router.patch(
    '/promotions/:promotionId/cancel',
    checkAuthMW,
    checkProductModeratorMW,
    promotionIdParamValidation,
    cancelProductPromotionByStaffController,
);
router.patch(
    '/promotions/:promotionId/extend',
    checkAuthMW,
    checkProductModeratorMW,
    promotionIdParamValidation,
    extendProductPromotionByStaffController,
);
router.post(
    '/:productId/promotions/request',
    checkAuthMW,
    productIdParamValidation,
    requestProductPromotionValidation,
    requestProductPromotionController,
);
router.get(
    '/moderation/pending/count',
    checkAuthMW,
    checkProductModeratorMW,
    getPendingModerationProductsCountController,
);
router.get(
    '/moderation/pending',
    checkAuthMW,
    checkProductModeratorMW,
    productsSearchValidation,
    getPendingModerationProductsController,
);
router.get(
    '/reports/pending/count',
    checkAuthMW,
    checkProductModeratorMW,
    getPendingProductReportsCountController,
);
router.get(
    '/reports/pending',
    checkAuthMW,
    checkProductModeratorMW,
    getPendingProductReportsController,
);
router.patch(
    '/reports/product/:productId/resolve',
    checkAuthMW,
    checkProductModeratorMW,
    productIdParamValidation,
    resolveProductReportsValidation,
    resolveProductReportsForProductController,
);
router.get(
    '/:productId/price-offers/top',
    productIdParamValidation,
    getTopProductPriceOffersController,
);
router.get(
    '/:productId/price-offers/me',
    checkAuthMW,
    productIdParamValidation,
    getMyProductPriceOfferController,
);
router.get(
    '/:productId/price-offers/archive',
    checkAuthMW,
    productIdParamValidation,
    getSellerProductPriceOfferArchiveController,
);
router.get(
    '/:productId/price-offers',
    checkAuthMW,
    productIdParamValidation,
    getSellerProductPriceOffersController,
);
router.post(
    '/:productId/price-offers',
    checkAuthMW,
    productPriceOfferRateLimiter,
    productIdParamValidation,
    submitProductPriceOfferValidation,
    submitProductPriceOfferController,
);
router.patch(
    '/:productId/price-offers/me',
    checkAuthMW,
    productPriceOfferRateLimiter,
    productIdParamValidation,
    patchProductPriceOfferValidation,
    patchMyProductPriceOfferController,
);
router.delete(
    '/:productId/price-offers/me',
    checkAuthMW,
    productIdParamValidation,
    cancelMyProductPriceOfferController,
);
router.patch(
    '/:productId/price-offers/:offerId/accept',
    checkAuthMW,
    productIdParamValidation,
    productPriceOfferIdParamValidation,
    acceptProductPriceOfferController,
);
router.patch(
    '/:productId/price-offers/:offerId/reject',
    checkAuthMW,
    productIdParamValidation,
    productPriceOfferIdParamValidation,
    rejectProductPriceOfferController,
);
router.get(
    '/:productId/catalog',
    productIdParamValidation,
    checkOptionalAuthMW,
    getCatalogProductByIdController,
);
router.get(
    '/:productId/reviews/summary',
    productIdParamValidation,
    checkOptionalAuthMW,
    getProductReviewSummaryController,
);
router.get(
    '/:productId/reviews',
    productIdParamValidation,
    productReviewsListValidation,
    listProductReviewsController,
);
router.post(
    '/:productId/reviews',
    checkAuthMW,
    productReviewRateLimiter,
    productIdParamValidation,
    submitProductReviewValidation,
    submitProductReviewController,
);
router.patch(
    '/:productId/reviews/me',
    checkAuthMW,
    productReviewRateLimiter,
    productIdParamValidation,
    patchProductReviewValidation,
    patchMyProductReviewController,
);
router.delete(
    '/:productId/reviews/me',
    checkAuthMW,
    productIdParamValidation,
    deleteMyProductReviewController,
);
router.get(
    '/:productId/report/me',
    checkAuthMW,
    productIdParamValidation,
    getMyProductReportStatusController,
);
router.post(
    '/:productId/report',
    checkAuthMW,
    productReportRateLimiter,
    productIdParamValidation,
    submitProductReportValidation,
    submitProductReportController,
);
router.post(
    '/:productId/view',
    checkAuthMW,
    productIdParamValidation,
    recordProductViewController,
);
router.patch(
    '/:productId/moderation/approve',
    checkAuthMW,
    checkProductModeratorMW,
    productIdParamValidation,
    approveProductModerationController,
);
router.patch(
    '/:productId/moderation/reject',
    checkAuthMW,
    checkProductModeratorMW,
    productIdParamValidation,
    rejectProductModerationValidation,
    rejectProductModerationController,
);
router.patch(
    '/:productId',
    checkAuthMW,
    productIdParamValidation,
    patchMyProductValidation,
    patchMyProductController,
);
router.delete(
    '/:productId',
    checkAuthMW,
    productIdParamValidation,
    deleteMyProductController,
);

export { router as productRouter };
