import { useCallback, useMemo } from "react";

/**
 * @param {object} params
 */
export const useHomeMainContentProps = ({
  isRaffleRoute,
  raffleRouteId,
  isSellerRoute,
  sellerRouteId,
  isAuthorized,
  isSessionReady,
  mainView,
  activeProfileTab,
  currentUserId,
  isAdmin,
  canModerateProducts,
  myProfilePage,
  usersListTick,
  notificationsPageItems,
  raffleRefreshTick,
  pendingRafflesCount,
  pendingModerationCount,
  pendingIncomingPriceOffersCount,
  pendingMySalesActionCount,
  pendingMyOrdersActionCount,
  pendingInstallmentBuyerActionCount,
  pendingInstallmentSellerActionCount,
  pendingInstallmentModerationCount,
  pendingInstallmentDisputesCount,
  pendingProductReportsCount,
  pendingDataConfirmationCount,
  catalogGridSection,
  catalogBrowserSection,
  setIsLoginModalOpen,
  handleSellerNameClick,
  handleCatalogProductClick,
  setCatalogProductDetails,
  goToMainView,
  setMyProfileTab,
  handleLogout,
  setIsEditProfileOpen,
  handleMyProductsFromProfile,
  handleMySalesFromProfile,
  handleInstallmentPaymentsFromProfile,
  handleInstallmentSalesFromProfile,
  handleInstallmentModerationFromProfile,
  handleInstallmentDisputesFromProfile,
  handleMyOrdersFromProfile,
  handleAuctionFromProfile,
  handleAdminOrdersFromProfile,
  handleSearchSynonymsAdminFromProfile,
  handleCategoryTreeAdminFromProfile,
  handleProductModerationFromProfile,
  handleProductReportsFromProfile,
  handleRafflesFromProfile,
  setRaffleModal,
  handleDataConfirmationQueueFromProfile,
  handleDataConfirmationFromProfile,
  setIsDataConfirmationModalOpen,
  dataConfirmationStatusRefreshTick,
  handlePremiumFromProfile,
  handlePremiumPurchased,
  handleLoyaltyPointsFromProfile,
  handleSubscriptionsFromProfile,
  refreshUserProfileActionBadgeCounts,
  refreshPendingModerationCount,
  refreshPendingProductReportsCount,
  refreshPendingRafflesCount,
  refreshPendingDataConfirmationCount,
  refreshPendingInstallmentModerationCount,
  refreshPendingInstallmentDisputesCount,
  refreshFeaturedRaffle,
  refreshSellerRaffleState,
  setRaffleRefreshTick,
  setCatalogRefreshTick,
  handleInAppNotificationClick,
  handleNotificationsCleared,
}) => {
  const onRequestLogin = useCallback(() => {
    setIsLoginModalOpen(true);
  }, [setIsLoginModalOpen]);

  const onEditProfileClick = useCallback(() => {
    setIsEditProfileOpen(true);
  }, [setIsEditProfileOpen]);

  const onCreateRaffleClick = useMemo(() => {
    if (
      myProfilePage.phase === "success" &&
      myProfilePage.user?.isUserDataConfirmed === true
    ) {
      return () => setRaffleModal({ mode: "create" });
    }
    return undefined;
  }, [myProfilePage, setRaffleModal]);

  return useMemo(
    () => ({
      isRaffleRoute,
      raffleRouteId,
      isSellerRoute,
      sellerRouteId,
      isAuthorized,
      isSessionReady,
      mainView,
      activeProfileTab,
      currentUserId,
      isAdmin,
      canModerateProducts,
      myProfilePage,
      usersListTick,
      notificationsPageItems,
      raffleRefreshTick,
      pendingRafflesCount,
      pendingModerationCount,
      pendingIncomingPriceOffersCount,
      pendingMySalesActionCount,
      pendingMyOrdersActionCount,
      pendingInstallmentBuyerActionCount,
      pendingInstallmentSellerActionCount,
      pendingInstallmentModerationCount,
      pendingInstallmentDisputesCount,
      pendingProductReportsCount,
      pendingDataConfirmationCount,
      catalogGridSection,
      catalogBrowserSection,
      onRequestLogin,
      onSellerNameClick: handleSellerNameClick,
      onCatalogProductClick: handleCatalogProductClick,
      onOpenProductDetails: setCatalogProductDetails,
      goToMainView,
      setMyProfileTab,
      handleLogout,
      onEditProfileClick,
      handleMyProductsFromProfile,
      handleMySalesFromProfile,
      handleInstallmentPaymentsFromProfile,
      handleInstallmentSalesFromProfile,
      handleInstallmentModerationFromProfile,
      handleInstallmentDisputesFromProfile,
      handleMyOrdersFromProfile,
      handleAuctionFromProfile,
      handleAdminOrdersFromProfile,
      handleSearchSynonymsAdminFromProfile,
      handleCategoryTreeAdminFromProfile,
      handleProductModerationFromProfile,
      handleProductReportsFromProfile,
      handleRafflesFromProfile,
      onCreateRaffleClick,
      handleDataConfirmationQueueFromProfile,
      handleDataConfirmationFromProfile,
      setIsDataConfirmationModalOpen,
      dataConfirmationStatusRefreshTick,
      handlePremiumFromProfile,
      handlePremiumPurchased,
      handleLoyaltyPointsFromProfile,
      handleSubscriptionsFromProfile,
      refreshUserProfileActionBadgeCounts,
      refreshPendingModerationCount,
      refreshPendingProductReportsCount,
      refreshPendingRafflesCount,
      refreshPendingDataConfirmationCount,
      refreshPendingInstallmentModerationCount,
      refreshPendingInstallmentDisputesCount,
      refreshFeaturedRaffle,
      refreshSellerRaffleState,
      setRaffleRefreshTick,
      setCatalogRefreshTick,
      setRaffleModal,
      handleInAppNotificationClick,
      handleNotificationsCleared,
    }),
    [
      isRaffleRoute,
      raffleRouteId,
      isSellerRoute,
      sellerRouteId,
      isAuthorized,
      isSessionReady,
      mainView,
      activeProfileTab,
      currentUserId,
      isAdmin,
      canModerateProducts,
      myProfilePage,
      usersListTick,
      notificationsPageItems,
      raffleRefreshTick,
      pendingRafflesCount,
      pendingModerationCount,
      pendingIncomingPriceOffersCount,
      pendingMySalesActionCount,
      pendingMyOrdersActionCount,
      pendingInstallmentBuyerActionCount,
      pendingInstallmentSellerActionCount,
      pendingInstallmentModerationCount,
      pendingInstallmentDisputesCount,
      pendingProductReportsCount,
      pendingDataConfirmationCount,
      catalogGridSection,
      catalogBrowserSection,
      onRequestLogin,
      handleSellerNameClick,
      handleCatalogProductClick,
      setCatalogProductDetails,
      goToMainView,
      setMyProfileTab,
      handleLogout,
      onEditProfileClick,
      handleMyProductsFromProfile,
      handleMySalesFromProfile,
      handleInstallmentPaymentsFromProfile,
      handleInstallmentSalesFromProfile,
      handleInstallmentModerationFromProfile,
      handleInstallmentDisputesFromProfile,
      handleMyOrdersFromProfile,
      handleAuctionFromProfile,
      handleAdminOrdersFromProfile,
      handleSearchSynonymsAdminFromProfile,
      handleCategoryTreeAdminFromProfile,
      handleProductModerationFromProfile,
      handleProductReportsFromProfile,
      handleRafflesFromProfile,
      onCreateRaffleClick,
      handleDataConfirmationQueueFromProfile,
      handleDataConfirmationFromProfile,
      setIsDataConfirmationModalOpen,
      dataConfirmationStatusRefreshTick,
      handlePremiumFromProfile,
      handlePremiumPurchased,
      handleLoyaltyPointsFromProfile,
      handleSubscriptionsFromProfile,
      refreshUserProfileActionBadgeCounts,
      refreshPendingModerationCount,
      refreshPendingProductReportsCount,
      refreshPendingRafflesCount,
      refreshPendingDataConfirmationCount,
      refreshPendingInstallmentModerationCount,
      refreshPendingInstallmentDisputesCount,
      refreshFeaturedRaffle,
      refreshSellerRaffleState,
      setRaffleRefreshTick,
      setCatalogRefreshTick,
      setRaffleModal,
      handleInAppNotificationClick,
      handleNotificationsCleared,
    ],
  );
};
