import { useCatalogMainContentProps } from "./useCatalogMainContentProps.js";
import { useHomeCatalogGridProps } from "./useHomeCatalogGridProps.js";
import { useHomeCatalogSections } from "./useHomeCatalogSections.jsx";
import { useHomeHeaderProps } from "./useHomeHeaderProps.js";
import { useHomeMainContentProps } from "./useHomeMainContentProps.js";
import { useHomeModalsLayerProps } from "./useHomeModalsLayerProps.js";

/**
 * Сборка header / main / modals props для HomePage.
 * @param {Record<string, unknown>} ctx
 */
export function useHomePagePresentationLayer(ctx) {
  const catalogGridSectionProps = useHomeCatalogGridProps({
    catalogStatus: ctx.catalogStatus,
    products: ctx.products,
    isHomeCatalogMainView: ctx.isHomeCatalogMainView,
    featuredRaffles: ctx.featuredRaffles,
    featuredRaffleIndex: ctx.featuredRaffleIndex,
    setFeaturedRaffleIndex: ctx.setFeaturedRaffleIndex,
    getFeaturedRaffleManage: ctx.getFeaturedRaffleManage,
    userStoriesFeed: ctx.userStoriesFeed,
    isAuthorized: ctx.isAuthorized,
    currentUserId: ctx.currentUserId,
    handleUserStoriesRefresh: ctx.handleUserStoriesRefresh,
    handleSellerNameClick: ctx.handleSellerNameClick,
    catalogMainView: ctx.catalogMainView,
    activeCatalogBrowserCategory: ctx.activeCatalogBrowserCategory,
    selectedProductCategory: ctx.selectedProductCategory,
    hasProductSearchQuery: ctx.hasProductSearchQuery,
    isMineMode: ctx.isMineMode,
    deletingProductId: ctx.deletingProductId,
    handleDeleteMyProduct: ctx.handleDeleteMyProduct,
    handleOpenEditMyProduct: ctx.handleOpenEditMyProduct,
    handleOpenPromotionModal: ctx.handleOpenPromotionModal,
    myProductsCatalogError: ctx.myProductsCatalogError,
    myProductsCatalogNotice: ctx.myProductsCatalogNotice,
    setCatalogProductDetails: ctx.setCatalogProductDetails,
    handleSetMyProductAvailability: ctx.handleSetMyProductAvailability,
    handleSetProductAuction: ctx.handleSetProductAuction,
    togglingAvailabilityProductId: ctx.togglingAvailabilityProductId,
    togglingAuctionProductId: ctx.togglingAuctionProductId,
    isPremiumUser: ctx.isPremiumUser,
    loyaltyPoints: ctx.loyaltyPoints,
    loyaltyPointsReserved: ctx.loyaltyPointsReserved,
    setIsLoginModalOpen: ctx.setIsLoginModalOpen,
    catalogSentinelRef: ctx.catalogSentinelRef,
    catalogHasMore: ctx.catalogHasMore,
    isCatalogLoadingMore: ctx.isCatalogLoadingMore,
    catalogLoadMoreError: ctx.catalogLoadMoreError,
    handleRetryCatalogLoadMore: ctx.handleRetryCatalogLoadMore,
    myProductsModerationFilter: ctx.myProductsModerationFilter,
    catalogFollowingOnly: ctx.catalogFollowingOnly,
    catalogAuctionOnly: ctx.catalogAuctionOnly,
    catalogInstallmentOnly: ctx.catalogInstallmentOnly,
    catalogSaleOnly: ctx.catalogSaleOnly,
    sellerRaffleActive: ctx.sellerRaffleActive,
    handleToggleRaffleParticipation: ctx.handleToggleRaffleParticipation,
    raffleParticipationPendingProductId: ctx.raffleParticipationPendingProductId,
  });

  const { catalogGridSection, catalogBrowserSection } = useHomeCatalogSections({
    catalogGridSectionProps,
    isCatalogBrowserLanding: ctx.isCatalogBrowserLanding,
    categoryDisplays: ctx.categoryDisplays,
    feedTileDisplays: ctx.feedTileDisplays,
    isAdmin: ctx.isAdmin,
    categoryDisplaysStatus: ctx.categoryDisplaysStatus,
    handleCatalogFeedTileClick: ctx.handleCatalogFeedTileClick,
    handleCatalogCategoryGridClick: ctx.handleCatalogCategoryGridClick,
    handleCatalogCategoryTreeSelect: ctx.handleCatalogCategoryTreeSelect,
    handleClearCatalogCategoryTreeFilter: ctx.handleClearCatalogCategoryTreeFilter,
    activeCatalogBrowserCategoryId: ctx.activeCatalogBrowserCategoryId,
    setEditingCategorySlug: ctx.setEditingCategorySlug,
    setEditingFeedTileKey: ctx.setEditingFeedTileKey,
    selectedCategoryLabel: ctx.selectedCategoryLabel,
    activeCatalogFeedLabel: ctx.activeCatalogFeedLabel,
    handleBackToCatalogLanding: ctx.handleBackToCatalogLanding,
  });

  const headerProps = useHomeHeaderProps({
    mainView: ctx.mainView,
    catalogMainView: ctx.catalogMainView,
    isMineMode: ctx.isMineMode,
    activeCatalogBrowserCategory: ctx.activeCatalogBrowserCategory,
    selectedProductCategory: ctx.selectedProductCategory,
    isProductCategoryListOpen: ctx.isProductCategoryListOpen,
    setIsProductCategoryListOpen: ctx.setIsProductCategoryListOpen,
    handleCatalogMenuClick: ctx.handleCatalogMenuClick,
    isCatalogBrowserLanding: ctx.isCatalogBrowserLanding,
    productSearchTerm: ctx.productSearchTerm,
    setProductSearchTerm: ctx.setProductSearchTerm,
    isProductSearchPending: ctx.isProductSearchPending,
    isAuthorized: ctx.isAuthorized,
    goToMainView: ctx.goToMainView,
    handleProductCategorySelect: ctx.handleProductCategorySelect,
    handlePlaceProductClick: ctx.handlePlaceProductClick,
    myProductsTotal: ctx.myProductsTotal,
    sellerProductsLimit: ctx.sellerProductsLimit,
    pendingModerationCount: ctx.pendingModerationCount,
    pendingInstallmentModerationCount: ctx.pendingInstallmentModerationCount,
    pendingInstallmentDisputesCount: ctx.pendingInstallmentDisputesCount,
    pendingProductReportsCount: ctx.pendingProductReportsCount,
    pendingDataConfirmationCount: ctx.pendingDataConfirmationCount,
    handleNotificationsClick: ctx.handleNotificationsClick,
    inAppNotificationsCount: ctx.inAppNotifications.length,
    setIsLoginModalOpen: ctx.setIsLoginModalOpen,
    setIsRegisterModalOpen: ctx.setIsRegisterModalOpen,
    handleNavigateToFullCatalogFromBreadcrumb:
      ctx.handleNavigateToFullCatalogFromBreadcrumb,
    catalogSort: ctx.catalogSort,
    handleCatalogSortChange: ctx.handleCatalogSortChange,
    catalogFollowingOnly: ctx.catalogFollowingOnly,
    catalogAuctionOnly: ctx.catalogAuctionOnly,
    catalogInstallmentOnly: ctx.catalogInstallmentOnly,
    catalogSaleOnly: ctx.catalogSaleOnly,
    handleCatalogFollowingOnlyToggle: ctx.handleCatalogFollowingOnlyToggle,
    handleCatalogAuctionOnlyToggle: ctx.handleCatalogAuctionOnlyToggle,
    handleCatalogInstallmentOnlyToggle: ctx.handleCatalogInstallmentOnlyToggle,
    handleCatalogSaleOnlyToggle: ctx.handleCatalogSaleOnlyToggle,
    isAdmin: ctx.isAdmin,
    canModerateProducts: ctx.canModerateProducts,
    showHiddenCatalogProducts: ctx.showHiddenCatalogProducts,
    handleShowHiddenCatalogProductsToggle: ctx.handleShowHiddenCatalogProductsToggle,
    myProductsModerationFilter: ctx.myProductsModerationFilter,
    setMyProductsModerationFilter: ctx.setMyProductsModerationFilter,
  });

  const mainContentProps = useHomeMainContentProps({
    isRaffleRoute: ctx.isRaffleRoute,
    raffleRouteId: ctx.raffleRouteId,
    isSellerRoute: ctx.isSellerRoute,
    sellerRouteId: ctx.sellerRouteId,
    isAuthorized: ctx.isAuthorized,
    isSessionReady: ctx.isSessionReady,
    mainView: ctx.mainView,
    activeProfileTab: ctx.activeProfileTab,
    currentUserId: ctx.currentUserId,
    isAdmin: ctx.isAdmin,
    canModerateProducts: ctx.canModerateProducts,
    myProfilePage: ctx.myProfilePage,
    usersListTick: ctx.usersListTick,
    notificationsPageItems: ctx.notificationsPageItems,
    raffleRefreshTick: ctx.raffleRefreshTick,
    pendingRafflesCount: ctx.pendingRafflesCount,
    pendingModerationCount: ctx.pendingModerationCount,
    pendingIncomingPriceOffersCount: ctx.pendingIncomingPriceOffersCount,
    pendingMySalesActionCount: ctx.pendingMySalesActionCount,
    pendingMyOrdersActionCount: ctx.pendingMyOrdersActionCount,
    pendingInstallmentBuyerActionCount: ctx.pendingInstallmentBuyerActionCount,
    pendingInstallmentSellerActionCount: ctx.pendingInstallmentSellerActionCount,
    pendingInstallmentModerationCount: ctx.pendingInstallmentModerationCount,
    pendingInstallmentDisputesCount: ctx.pendingInstallmentDisputesCount,
    pendingProductReportsCount: ctx.pendingProductReportsCount,
    pendingDataConfirmationCount: ctx.pendingDataConfirmationCount,
    catalogGridSection,
    catalogBrowserSection,
    myProductsCatalogToolbarProps: {
      catalogSort: ctx.catalogSort,
      onCatalogSortChange: ctx.handleCatalogSortChange,
      isAdmin: ctx.isAdmin,
      myProductsTotal: ctx.myProductsTotal,
      sellerProductsLimit: ctx.sellerProductsLimit,
      myProductsModerationFilter: ctx.myProductsModerationFilter,
      onMyProductsModerationFilterChange: ctx.setMyProductsModerationFilter,
    },
    setIsLoginModalOpen: ctx.setIsLoginModalOpen,
    handleSellerNameClick: ctx.handleSellerNameClick,
    handleCatalogProductClick: ctx.handleCatalogProductClick,
    setCatalogProductDetails: ctx.setCatalogProductDetails,
    goToMainView: ctx.goToMainView,
    setMyProfileTab: ctx.setMyProfileTab,
    handleLogout: ctx.handleLogout,
    setIsEditProfileOpen: ctx.setIsEditProfileOpen,
    handleMyProductsFromProfile: ctx.handleMyProductsFromProfile,
    handleMySalesFromProfile: ctx.handleMySalesFromProfile,
    handleInstallmentPaymentsFromProfile: ctx.handleInstallmentPaymentsFromProfile,
    handleInstallmentSalesFromProfile: ctx.handleInstallmentSalesFromProfile,
    handleInstallmentModerationFromProfile: ctx.handleInstallmentModerationFromProfile,
    handleInstallmentDisputesFromProfile: ctx.handleInstallmentDisputesFromProfile,
    handleMyOrdersFromProfile: ctx.handleMyOrdersFromProfile,
    handleAuctionFromProfile: ctx.handleAuctionFromProfile,
    handleAdminOrdersFromProfile: ctx.handleAdminOrdersFromProfile,
    handleSearchSynonymsAdminFromProfile: ctx.handleSearchSynonymsAdminFromProfile,
    handleCategoryTreeAdminFromProfile: ctx.handleCategoryTreeAdminFromProfile,
    handleProductModerationFromProfile: ctx.handleProductModerationFromProfile,
    handleProductReportsFromProfile: ctx.handleProductReportsFromProfile,
    handleRafflesFromProfile: ctx.handleRafflesFromProfile,
    setRaffleModal: ctx.setRaffleModal,
    handleDataConfirmationQueueFromProfile: ctx.handleDataConfirmationQueueFromProfile,
    handleDataConfirmationFromProfile: ctx.handleDataConfirmationFromProfile,
    setIsDataConfirmationModalOpen: ctx.setIsDataConfirmationModalOpen,
    dataConfirmationStatusRefreshTick: ctx.dataConfirmationStatusRefreshTick,
    handlePremiumFromProfile: ctx.handlePremiumFromProfile,
    handlePremiumPurchased: ctx.handlePremiumPurchased,
    handleLoyaltyPointsFromProfile: ctx.handleLoyaltyPointsFromProfile,
    handleSubscriptionsFromProfile: ctx.handleSubscriptionsFromProfile,
    refreshUserProfileActionBadgeCounts: ctx.refreshUserProfileActionBadgeCounts,
    refreshPendingModerationCount: ctx.refreshPendingModerationCount,
    refreshPendingProductReportsCount: ctx.refreshPendingProductReportsCount,
    refreshPendingRafflesCount: ctx.refreshPendingRafflesCount,
    refreshPendingDataConfirmationCount: ctx.refreshPendingDataConfirmationCount,
    refreshPendingInstallmentModerationCount:
      ctx.refreshPendingInstallmentModerationCount,
    refreshPendingInstallmentDisputesCount: ctx.refreshPendingInstallmentDisputesCount,
    refreshFeaturedRaffle: ctx.refreshFeaturedRaffle,
    refreshSellerRaffleState: ctx.refreshSellerRaffleState,
    setRaffleRefreshTick: ctx.setRaffleRefreshTick,
    setCatalogRefreshTick: ctx.setCatalogRefreshTick,
    handleInAppNotificationClick: ctx.handleInAppNotificationClick,
    handleNotificationsCleared: ctx.handleNotificationsCleared,
  });

  const modalsLayerProps = useHomeModalsLayerProps({
    sellerModal: ctx.sellerModal,
    closeSellerModal: ctx.closeSellerModal,
    renderSellerFollowAccessory: ctx.renderSellerFollowAccessory,
    currentUserId: ctx.currentUserId,
    isAuthorized: ctx.isAuthorized,
    isPremiumUser: ctx.isPremiumUser,
    canModerateProducts: ctx.canModerateProducts,
    isAdmin: ctx.isAdmin,
    setIsAdminEditUserOpen: ctx.setIsAdminEditUserOpen,
    setIsAdminDeleteUserOpen: ctx.setIsAdminDeleteUserOpen,
    setUsersListTick: ctx.setUsersListTick,
    setSellerModal: ctx.setSellerModal,
    setIsLoginModalOpen: ctx.setIsLoginModalOpen,
    isDataConfirmationModalOpen: ctx.isDataConfirmationModalOpen,
    setIsDataConfirmationModalOpen: ctx.setIsDataConfirmationModalOpen,
    setDataConfirmationStatusRefreshTick: ctx.setDataConfirmationStatusRefreshTick,
    refreshPendingDataConfirmationCount: ctx.refreshPendingDataConfirmationCount,
    isEditProfileOpen: ctx.isEditProfileOpen,
    setIsEditProfileOpen: ctx.setIsEditProfileOpen,
    myProfilePage: ctx.myProfilePage,
    setMyProfilePage: ctx.setMyProfilePage,
    setIsPremiumUser: ctx.setIsPremiumUser,
    setLoyaltyPoints: ctx.setLoyaltyPoints,
    isAdminEditUserOpen: ctx.isAdminEditUserOpen,
    isAdminDeleteUserOpen: ctx.isAdminDeleteUserOpen,
    setCatalogProductDetails: ctx.setCatalogProductDetails,
    setCatalogRefreshTick: ctx.setCatalogRefreshTick,
    setProducts: ctx.setProducts,
    isLoginModalOpen: ctx.isLoginModalOpen,
    setIsAuthorized: ctx.setIsAuthorized,
    isRegisterModalOpen: ctx.isRegisterModalOpen,
    setIsRegisterModalOpen: ctx.setIsRegisterModalOpen,
    isEmailVerificationModalOpen: ctx.isEmailVerificationModalOpen,
    currentUserEmail: ctx.currentUserEmail,
    handleEmailVerificationModalClose: ctx.handleEmailVerificationModalClose,
    setIsEmailVerified: ctx.setIsEmailVerified,
    isSellerProductsLimitModalOpen: ctx.isSellerProductsLimitModalOpen,
    setIsSellerProductsLimitModalOpen: ctx.setIsSellerProductsLimitModalOpen,
    sellerProductsLimit: ctx.sellerProductsLimit,
    isCreateProductModalOpen: ctx.isCreateProductModalOpen,
    setIsCreateProductModalOpen: ctx.setIsCreateProductModalOpen,
    handleCreateProductSuccess: ctx.handleCreateProductSuccess,
    loyaltyPoints: ctx.loyaltyPoints,
    loyaltyPointsReserved: ctx.loyaltyPointsReserved,
    isMineMode: ctx.isMineMode,
    products: ctx.products,
    productToEdit: ctx.productToEdit,
    handleCloseEditProductModal: ctx.handleCloseEditProductModal,
    handleEditProductSuccess: ctx.handleEditProductSuccess,
    handleDeleteMyProduct: ctx.handleDeleteMyProduct,
    handleSetMyProductAvailability: ctx.handleSetMyProductAvailability,
    handleSetProductAuction: ctx.handleSetProductAuction,
    deletingProductId: ctx.deletingProductId,
    togglingAvailabilityProductId: ctx.togglingAvailabilityProductId,
    togglingAuctionProductId: ctx.togglingAuctionProductId,
    myProductsCatalogError: ctx.myProductsCatalogError,
    productDetailsAdminError: ctx.productDetailsAdminError,
    sellerRaffleActive: ctx.sellerRaffleActive,
    handleToggleRaffleParticipation: ctx.handleToggleRaffleParticipation,
    raffleParticipationPendingProductId: ctx.raffleParticipationPendingProductId,
    promotionProduct: ctx.promotionProduct,
    promotionConfig: ctx.promotionConfig,
    promotionModalError: ctx.promotionModalError,
    isPromotionSubmitPending: ctx.isPromotionSubmitPending,
    handleClosePromotionModal: ctx.handleClosePromotionModal,
    handleSubmitPromotionRequest: ctx.handleSubmitPromotionRequest,
    raffleModal: ctx.raffleModal,
    setRaffleModal: ctx.setRaffleModal,
    setRaffleRefreshTick: ctx.setRaffleRefreshTick,
    refreshFeaturedRaffle: ctx.refreshFeaturedRaffle,
    refreshSellerRaffleState: ctx.refreshSellerRaffleState,
    refreshPendingRafflesCount: ctx.refreshPendingRafflesCount,
    setMyProductsCatalogNotice: ctx.setMyProductsCatalogNotice,
    setStaffActionNotice: ctx.setStaffActionNotice,
    catalogProductDetails: ctx.catalogProductDetails,
    setCatalogProductDetailsTab: ctx.setCatalogProductDetailsTab,
    setProductDetailsAdminError: ctx.setProductDetailsAdminError,
    handleSellerNameClick: ctx.handleSellerNameClick,
    goToSellerProducts: ctx.goToSellerProducts,
    handleProductStatsUpdate: ctx.handleProductStatsUpdate,
    catalogDetailsShowAddToCart: ctx.catalogDetailsShowAddToCart,
    catalogProductDetailsTab: ctx.catalogProductDetailsTab,
    refreshUserProfileActionBadgeCounts: ctx.refreshUserProfileActionBadgeCounts,
    canReportCatalogProduct: ctx.canReportCatalogProduct,
    catalogProductHasPendingReport: ctx.catalogProductHasPendingReport,
    setIsReportProductModalOpen: ctx.setIsReportProductModalOpen,
    showCatalogProductManageFooter: ctx.showCatalogProductManageFooter,
    handleAdminOpenEditProductFromDetails: ctx.handleAdminOpenEditProductFromDetails,
    isReportProductModalOpen: ctx.isReportProductModalOpen,
    setCatalogProductHasPendingReport: ctx.setCatalogProductHasPendingReport,
    editingCategorySlug: ctx.editingCategorySlug,
    setEditingCategorySlug: ctx.setEditingCategorySlug,
    editingFeedTileKey: ctx.editingFeedTileKey,
    setEditingFeedTileKey: ctx.setEditingFeedTileKey,
    categoryDisplays: ctx.categoryDisplays,
    feedTileDisplays: ctx.feedTileDisplays,
    handleCategoryDisplaySaved: ctx.handleCategoryDisplaySaved,
    handleFeedTileDisplaySaved: ctx.handleFeedTileDisplaySaved,
  });

  const catalogContentProps = useCatalogMainContentProps({
    catalogMainView: ctx.catalogMainView,
    catalogGridSection,
    catalogBrowserSection,
  });

  return {
    headerProps,
    catalogContentProps,
    accountContentProps: mainContentProps,
    mainContentProps,
    modalsLayerProps,
  };
}
