import { useMemo } from "react";

/** @typedef {import('../../../entities/product/model/types.js').ProductFromApi} ProductFromApi */

/**
 * @param {object} params
 */
export const useHomeCatalogGridProps = ({
  catalogStatus,
  products,
  isHomeCatalogMainView,
  featuredRaffles,
  featuredRaffleIndex,
  setFeaturedRaffleIndex,
  getFeaturedRaffleManage,
  userStoriesFeed,
  isAuthorized,
  currentUserId,
  handleUserStoriesRefresh,
  handleSellerNameClick,
  catalogMainView,
  activeCatalogBrowserCategory,
  selectedProductCategory,
  hasProductSearchQuery,
  isMineMode,
  deletingProductId,
  handleDeleteMyProduct,
  handleOpenEditMyProduct,
  handleOpenPromotionModal,
  myProductsCatalogError,
  myProductsCatalogNotice,
  setCatalogProductDetails,
  handleSetMyProductAvailability,
  handleSetProductAuction,
  togglingAvailabilityProductId,
  togglingAuctionProductId,
  isPremiumUser,
  loyaltyPoints,
  loyaltyPointsReserved,
  setIsLoginModalOpen,
  catalogSentinelRef,
  catalogHasMore,
  isCatalogLoadingMore,
  catalogLoadMoreError,
  handleRetryCatalogLoadMore,
  myProductsModerationFilter,
  catalogFollowingOnly,
  catalogAuctionOnly,
  catalogInstallmentOnly,
  catalogSaleOnly,
  sellerRaffleActive,
  handleToggleRaffleParticipation,
  raffleParticipationPendingProductId,
}) => {
  return useMemo(
    () => ({
      catalogStatus,
      products,
      isHomeCatalogMainView,
      featuredRaffles,
      featuredRaffleIndex,
      onFeaturedRaffleIndexChange: setFeaturedRaffleIndex,
      getFeaturedRaffleManage,
      userStoriesFeed,
      isAuthorized,
      currentUserId,
      onUserStoriesRefresh: handleUserStoriesRefresh,
      onSellerNameClick: handleSellerNameClick,
      catalogMainView,
      activeCatalogBrowserCategory,
      selectedProductCategory,
      hasProductSearchQuery,
      isMineMode,
      deletingProductId,
      onDeleteMyProduct: handleDeleteMyProduct,
      onEditMyProduct: handleOpenEditMyProduct,
      onPromoteMyProduct: handleOpenPromotionModal,
      myProductsCatalogError,
      myProductsCatalogNotice,
      onOpenProductDetails: setCatalogProductDetails,
      onSetMyProductAvailability: handleSetMyProductAvailability,
      onSetMyProductAuction: handleSetProductAuction,
      togglingAvailabilityProductId,
      togglingAuctionProductId,
      isPremiumUser,
      sellerLoyaltyPointsBalance: loyaltyPoints,
      sellerLoyaltyPointsReserved: loyaltyPointsReserved,
      onRequestLoginAddToCart: () => setIsLoginModalOpen(true),
      catalogSentinelRef,
      catalogHasMore,
      isCatalogLoadingMore,
      catalogLoadMoreError,
      onRetryCatalogLoadMore: handleRetryCatalogLoadMore,
      myProductsModerationFilter,
      catalogFollowingOnly,
      catalogAuctionOnly,
      catalogInstallmentOnly,
      catalogSaleOnly,
      showFullWidthTier3Banners:
        !isMineMode &&
        !selectedProductCategory &&
        !hasProductSearchQuery &&
        !catalogFollowingOnly &&
        !catalogAuctionOnly &&
        !catalogInstallmentOnly &&
        !catalogSaleOnly,
      sellerRaffleActive,
      raffleParticipationPendingProductId,
    }),
    [
      catalogStatus,
      products,
      isHomeCatalogMainView,
      featuredRaffles,
      featuredRaffleIndex,
      setFeaturedRaffleIndex,
      getFeaturedRaffleManage,
      userStoriesFeed,
      isAuthorized,
      currentUserId,
      handleUserStoriesRefresh,
      handleSellerNameClick,
      catalogMainView,
      activeCatalogBrowserCategory,
      selectedProductCategory,
      hasProductSearchQuery,
      isMineMode,
      deletingProductId,
      handleDeleteMyProduct,
      handleOpenEditMyProduct,
      handleOpenPromotionModal,
      myProductsCatalogError,
      myProductsCatalogNotice,
      setCatalogProductDetails,
      handleSetMyProductAvailability,
      handleSetProductAuction,
      togglingAvailabilityProductId,
      togglingAuctionProductId,
      isPremiumUser,
      loyaltyPoints,
      loyaltyPointsReserved,
      setIsLoginModalOpen,
      catalogSentinelRef,
      catalogHasMore,
      isCatalogLoadingMore,
      catalogLoadMoreError,
      handleRetryCatalogLoadMore,
      myProductsModerationFilter,
      catalogFollowingOnly,
      catalogAuctionOnly,
      catalogInstallmentOnly,
      catalogSaleOnly,
      sellerRaffleActive,
      handleToggleRaffleParticipation,
      raffleParticipationPendingProductId,
    ],
  );
};
