/** Паритет client `CreateUserStoryModal.css` + `createUserStoryModalAnimation.js`. */
export const CREATE_USER_STORY_MODAL_LAYOUT = {
  enterMs: 420,
  exitMs: 420,
  heightRatio: 0.8,
  borderRadius: 32,
  maxWidthWide: 416,
  wideBreakpoint: 641,
  backdropScrim: "rgba(0,0,0,0.62)",
  previewMaxHeight: 220,
  captionHeight: 180,
  headerMarginBottom: 12,
  previewMarginBottom: 14,
  bodyPaddingTop: 16,
  bodyPaddingHorizontal: 12,
  bodyPaddingBottom: 12,
  captionLabelGap: 6,
  captionPaddingVertical: 8,
  captionPaddingHorizontal: 10,
  captionBorderRadius: 10,
  captionFontSize: 16,
  footerPaddingTop: 10,
  footerPaddingHorizontal: 12,
  footerPaddingBottomMin: 12,
  submitBorderRadius: 14,
  submitFontSize: 15,
  closeFontSize: 12,
  dismissGuardMs: 700,
  sheetEnterEasing: [0.215, 0.61, 0.355, 1] as const,
  sheetEnterEasingCss: "cubic-bezier(0.215, 0.61, 0.355, 1)",
} as const;
