import { StyleSheet } from "react-native";

import { MODAL_BACKDROP_SCRIM } from "@/shared/theme/formChromeStyles";
import { SCREEN_CONTENT_PADDING_HORIZONTAL } from "@/shared/theme/screenContentLayout";
import { createThemedStyles } from "@/shared/theme/createThemedStyles";

export const useCreateRafflePageStyles = createThemedStyles((theme) => ({
  container: {
    flex: 1,
    minHeight: 0,
    backgroundColor: theme.colors.bg,
  },
  scroll: {
    flexGrow: 1,
  },
  content: {
    gap: 12,
    paddingHorizontal: SCREEN_CONTENT_PADDING_HORIZONTAL,
    paddingTop: 12,
    backgroundColor: theme.colors.bg,
  },
  header: {
    marginBottom: 4,
  },
  form: {
    gap: 10,
  },
  wizardProgress: {
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.actionBorder,
    backgroundColor: theme.colors.actionSoft,
  },
  wizardCaption: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: theme.colors.action,
  },
  wizardSteps: {
    flexDirection: "row",
    gap: 6,
  },
  wizardStep: {
    flex: 1,
    alignItems: "center",
    gap: 4,
    opacity: 0.55,
  },
  wizardStepActive: {
    opacity: 1,
  },
  wizardStepComplete: {
    opacity: 1,
  },
  wizardStepIndex: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.surface,
  },
  wizardStepIndexActive: {
    borderColor: theme.colors.action,
    backgroundColor: theme.colors.action,
  },
  wizardStepIndexComplete: {
    borderColor: theme.colors.success,
    backgroundColor: theme.colors.successSurface,
  },
  wizardStepIndexText: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.colors.textSecondary,
  },
  wizardStepIndexTextActive: {
    color: theme.colors.onContrast,
  },
  wizardStepIndexTextComplete: {
    color: theme.colors.successText,
  },
  wizardStepLabel: {
    fontSize: 10,
    lineHeight: 12,
    textAlign: "center",
    color: theme.colors.textSecondary,
  },
  stepHeadline: {
    gap: 4,
    marginTop: 4,
  },
  stepTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: theme.colors.primary,
  },
  stepSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: theme.colors.textSecondary,
  },
  wizardFooter: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.border,
  },
  wizardSecondaryBtn: {
    flex: 1,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 12,
  },
  wizardCancelBtn: {
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
  },
  wizardSecondaryBtnText: {
    fontSize: 15,
    fontWeight: "700",
    color: theme.colors.textSecondary,
  },
  wizardPrimaryBtn: {
    flex: 1.4,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    borderWidth: 1,
    borderColor: theme.colors.action,
    backgroundColor: theme.colors.action,
    paddingHorizontal: 12,
  },
  wizardPrimaryBtnText: {
    fontSize: 15,
    fontWeight: "700",
    color: theme.colors.onContrast,
  },
  section: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.border,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: theme.colors.surface,
    shadowColor: theme.colors.ink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  sectionTitle: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.actionBorder,
    backgroundColor: theme.colors.action,
    fontSize: 11.5,
    fontWeight: "800",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: theme.colors.onContrast,
  },
  sectionBody: {
    gap: 12,
    padding: 12,
  },
  field: {
    gap: 5.6,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.text,
  },
  fieldHint: {
    fontSize: 12.48,
    lineHeight: 17.5,
    color: theme.colors.textMuted,
  },
  input: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.border,
    borderRadius: 8,
    paddingHorizontal: 8.8,
    paddingVertical: 7.2,
    fontSize: 15,
    color: theme.colors.text,
    backgroundColor: theme.colors.surfaceMuted,
  },
  textarea: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  mediaType: {
    gap: 8,
    padding: 10,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.actionBorder,
    backgroundColor: theme.colors.actionSoft,
  },
  mediaTypeLegend: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.text,
  },
  mediaTypeOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  mediaTypeOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  mediaTypeOptionActive: {
    opacity: 1,
  },
  mediaTypeOptionText: {
    fontSize: 14,
    color: theme.colors.text,
  },
  mediaTypeDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.borderStrong,
    alignItems: "center",
    justifyContent: "center",
  },
  mediaTypeDotActive: {
    borderColor: theme.colors.action,
  },
  mediaTypeDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.colors.action,
  },
  pageHint: {
    fontSize: 12.8,
    lineHeight: 17.9,
    color: theme.colors.action,
    paddingHorizontal: 4,
  },
  blockNotice: {
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.danger,
    backgroundColor: theme.colors.surfaceMuted,
  },
  blockNoticeText: {
    fontSize: 13.6,
    lineHeight: 19.5,
    color: theme.colors.danger,
  },
  blockNoticeBtn: {
    alignSelf: "flex-start",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: theme.colors.danger,
  },
  blockNoticeBtnText: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.onContrast,
  },
  error: {
    fontSize: 13.6,
    lineHeight: 19.5,
    color: theme.colors.danger,
  },
  success: {
    fontSize: 13.6,
    lineHeight: 19.5,
    color: theme.colors.success,
  },
  actions: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    marginTop: 4,
  },
  submit: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.action,
    backgroundColor: theme.colors.action,
    alignSelf: "center",
  },
  submitDisabled: {
    opacity: 0.55,
  },
  submitText: {
    fontSize: 15,
    fontWeight: "600",
    color: theme.colors.onContrast,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: SCREEN_CONTENT_PADDING_HORIZONTAL,
    backgroundColor: theme.colors.bg,
  },
  state: {
    fontSize: 14.72,
    lineHeight: 21.3,
    color: theme.colors.textSecondary,
    textAlign: "center",
    paddingVertical: 5.6,
    paddingHorizontal: 2.4,
  },
  hint: {
    fontSize: 14.72,
    lineHeight: 21.3,
    color: theme.colors.textSecondary,
    textAlign: "center",
    paddingVertical: 5.6,
    paddingHorizontal: 2.4,
  },
  loginButton: {
    alignSelf: "stretch",
    minHeight: 40.8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10.4,
    backgroundColor: theme.colors.action,
    alignItems: "center",
    justifyContent: "center",
  },
  loginButtonText: {
    color: theme.colors.onContrast,
    fontWeight: "600",
    fontSize: 14.4,
  },
}));

export const useCreateRaffleModalStyles = createThemedStyles((theme) => ({
  overlay: {
    flex: 1,
    backgroundColor: MODAL_BACKDROP_SCRIM,
  },
  backdropPressable: {
    ...StyleSheet.absoluteFillObject,
  },
  card: {
    flex: 1,
    width: "100%",
    maxHeight: "100%",
    borderRadius: 0,
    borderWidth: 0,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: theme.colors.surface,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.border,
  },
  title: {
    flex: 1,
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.text,
  },
  closeButton: {
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  closeText: {
    fontSize: 28,
    lineHeight: 28,
    color: theme.colors.textMuted,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 8,
  },
}));
