import { izColors } from "@izibuy/design-tokens";

/** Canonical semantic colors — synced with design-tokens v2. */
export const semanticColors = {
  text: izColors.text,
  textMuted: izColors.textMuted,
  textSecondary: izColors.textSecondary,
  ink: izColors.ink,
  bg: izColors.bg,
  surface: izColors.surface,
  surfaceMuted: izColors.surfaceMuted,
  surfaceElevated: izColors.surfaceElevated,
  border: izColors.border,
  borderStrong: izColors.borderStrong,
  action: izColors.action,
  actionHover: izColors.actionHover,
  actionSoft: izColors.actionSoft,
  actionBorder: izColors.actionBorder,
  link: izColors.link,
  success: izColors.success,
  successSurface: izColors.successSurface,
  successText: izColors.successText,
  warning: izColors.warning,
  warningSurface: izColors.warningSurface,
  warningText: izColors.warningText,
  danger: izColors.danger,
  dangerSurface: izColors.dangerSurface,
  dangerText: izColors.dangerText,
  accent: izColors.accent,
  accentSoft: izColors.accentSoft,
  info: izColors.info,
  infoSoft: izColors.infoSoft,
  infoDeep: izColors.infoDeep,
  onContrast: izColors.onContrast,
  overlay: izColors.overlay,
  overlayStrong: izColors.overlayStrong,
  focusRing: izColors.focusRing,
} as const;
