import { Platform, StyleSheet } from "react-native";

import { WHOLESALE_PRICE_SHEET_LAYOUT as WS } from "@/entities/product/lib/wholesalePriceSheetLayout";
import { createThemedStyles } from "@/shared/theme/createThemedStyles";

export const useWholesalePriceSheetStyles = createThemedStyles((theme) => ({
  backdrop: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  dismiss: {
    ...StyleSheet.absoluteFillObject,
  },
  panel: {
    width: "100%",
    maxWidth: WS.maxWidth,
    maxHeight: "92%",
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: WS.borderTopRadius,
    borderTopRightRadius: WS.borderTopRadius,
    overflow: "hidden",
    ...(Platform.OS === "ios" ? { borderCurve: "continuous" as const } : null),
    shadowColor: theme.colors.ink,
    shadowOffset: { width: 0, height: -12 },
    shadowOpacity: 0.18,
    shadowRadius: 40,
    elevation: 16,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingTop: WS.headerPaddingTop,
    paddingHorizontal: WS.headerPaddingHorizontal,
    paddingBottom: WS.headerPaddingBottom,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.colors.border,
  },
  title: {
    flex: 1,
    minWidth: 0,
    fontSize: WS.titleFontSize,
    fontWeight: "700",
    lineHeight: WS.titleLineHeight,
    color: theme.colors.text,
  },
  close: {
    flexShrink: 0,
    paddingVertical: 4,
    paddingHorizontal: 2.4,
    fontSize: WS.closeFontSize,
    fontWeight: "600",
    color: theme.colors.link,
  },
  bodyScroll: {
    flexGrow: 0,
    flexShrink: 1,
  },
  body: {
    gap: WS.bodyGap,
    padding: WS.bodyPadding,
  },
  hint: {
    margin: 0,
    fontSize: WS.hintFontSize,
    lineHeight: WS.hintLineHeight,
    color: theme.colors.textMuted,
  },
  field: {
    gap: WS.fieldGap,
  },
  label: {
    fontSize: WS.labelFontSize,
    fontWeight: "600",
    color: theme.colors.ink,
  },
  input: {
    width: "100%",
    minHeight: WS.inputMinHeight,
    paddingVertical: WS.inputPaddingVertical,
    paddingHorizontal: WS.inputPaddingHorizontal,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: WS.inputBorderRadius,
    backgroundColor: theme.colors.surfaceMuted,
    color: theme.colors.text,
    fontSize: WS.inputFontSize,
  },
  promoApplied: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: WS.promoAppliedPaddingVertical,
    paddingHorizontal: WS.promoAppliedPaddingHorizontal,
    borderWidth: 1,
    borderColor: `${theme.colors.success}47`,
    borderRadius: WS.promoAppliedBorderRadius,
    backgroundColor: theme.colors.successSurface,
  },
  promoAppliedLabel: {
    flex: 1,
    fontSize: WS.promoAppliedLabelFontSize,
    fontWeight: "600",
    lineHeight: 19.76,
    color: theme.colors.successText,
  },
  promoAppliedPercent: {
    flexShrink: 0,
    paddingVertical: WS.promoAppliedPercentPaddingVertical,
    paddingHorizontal: WS.promoAppliedPercentPaddingHorizontal,
    borderRadius: 999,
    backgroundColor: theme.colors.success,
    color: theme.colors.onContrast,
    fontSize: WS.promoAppliedPercentFontSize,
    fontWeight: "800",
    lineHeight: 20.16,
    overflow: "hidden",
  },
  promoAppliedSuccess: {
    fontSize: WS.promoAppliedLabelFontSize,
    fontWeight: "600",
    lineHeight: 19.76,
    color: theme.colors.successText,
  },
  error: {
    margin: 0,
    fontSize: WS.errorFontSize,
    color: theme.colors.danger,
  },
  footer: {
    paddingTop: WS.footerPaddingVertical,
    paddingHorizontal: WS.footerPaddingHorizontal,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
  },
  footerButton: {
    width: "100%",
    minHeight: WS.inputMinHeight,
  },
}));
