/** Паритет `ProductDetailsFeatureCard.css` + `ProductDetailsModalPrice.css` feature-cards. */
export const PRODUCT_DETAILS_FEATURE_CARD_LAYOUT = {
  cardGap: 14,
  cardPaddingVertical: 12,
  cardPaddingHorizontal: 14,
  cardBorderRadius: 14,
  cardBorderWidth: 1,
  iconSize: 44,
  iconRadius: 12,
  iconGlyphSize: 20,
  iconStrokeWidth: 2.25,
  chevronSize: 18,
  chevronStrokeWidth: 2.5,
  chevronOpacity: 0.85,
  textGap: 2,
  titleFontSize: 15.2,
  titleLineHeight: 19,
  titleFontWeight: "700" as const,
  subtitleFontSize: 13.12,
  subtitleLineHeight: 17.056,
  subtitleFontWeight: "500" as const,
  gridGap: 10,
  gridPadding: 12,
  gridBorderRadius: 16,
  gridBorderWidth: 1,
  gridSplitMinCellWidth: 192,
  disabledOpacity: 0.65,
} as const;
