/** Паритет `ProductDetailsSellerProductsCarousel.css`. */
export const PRODUCT_DETAILS_SELLER_PRODUCTS_CAROUSEL_LAYOUT = {
  borderRadius: 16,
  borderWidth: 1,
  headingPaddingTop: 8,
  headingPaddingHorizontal: 14,
  headingPaddingBottom: 4,
  headingFontSize: 13,
  headingFontWeight: "700" as const,
  headingLetterSpacing: 0.2,
  headingLineHeight: 16.25,
  trackPaddingTop: 4,
  trackPaddingHorizontal: 14,
  trackPaddingBottom: 12,
  trackGap: 10,
  thumbSize: 64,
  thumbRadius: 18,
  thumbBorderWidth: 1,
  thumbCurrentOutlineWidth: 2,
  thumbUnavailableOpacity: 0.72,
  errorFontSize: 12,
  errorPaddingHorizontal: 14,
  errorPaddingBottom: 10,
} as const;
