/** Паритет `ProductPickupDetailsPanel.css`. */
export const PRODUCT_PICKUP_DETAILS_PANEL_LAYOUT = {
  panelGap: 10,
  methodGap: 14,
  methodPaddingVertical: 12,
  methodPaddingHorizontal: 14,
  methodBorderRadius: 14,
  methodBorderWidth: 1,
  iconSize: 44,
  iconRadius: 12,
  iconGlyphSize: 20,
  iconStrokeWidth: 2.25,
  textGap: 2,
  titleFontSize: 15.2,
  titleLineHeight: 19,
  titleFontWeight: "700" as const,
  subtitleFontSize: 13.12,
  subtitleLineHeight: 17.056,
  subtitleFontWeight: "500" as const,
  actionMaxWidth: 120,
  actionPaddingVertical: 8,
  actionPaddingHorizontal: 11.2,
  actionBorderRadius: 12,
  actionFontSize: 12,
  actionLineHeight: 14.4,
  actionFontWeight: "700" as const,
} as const;
