export const PRODUCT_CARD_GALLERY_DOT_WIDTH = 5;
export const PRODUCT_CARD_GALLERY_DOT_ACTIVE_WIDTH = 16;
export const PRODUCT_CARD_GALLERY_DOT_HEIGHT = 5;
export const PRODUCT_CARD_GALLERY_DOT_GAP = 4;
