/** Паритет `ProductDetailsSellerPreview.css` + page split overrides. */
export const PRODUCT_DETAILS_SELLER_PREVIEW_LAYOUT = {
  rootPadding: 14,
  rootGap: 14,
  rootBorderRadius: 16,
  rootBorderWidth: 1,
  rootMarginTop: 8,
  rootMarginHorizontal: 16,
  headerGap: 12,
  headerTextGap: 3.2,
  avatarSize: 56,
  labelFontSize: 11,
  labelLetterSpacing: 0.66,
  labelFontWeight: "700" as const,
  nameFontSize: 16.8,
  nameLineHeight: 21.84,
  nameFontWeight: "700" as const,
  chevronSize: 20,
  chevronOpacity: 0.9,
  metricsGap: 8,
  metricGap: 10,
  metricPaddingVertical: 10,
  metricPaddingHorizontal: 11.2,
  metricBorderRadius: 12,
  metricIconSize: 30,
  metricIconRadius: 8,
  metricBodyGap: 1.6,
  metricValueFontSize: 15.2,
  metricValueLineHeight: 19,
  metricValueFontWeight: "700" as const,
  metricKeyFontSize: 11,
  metricKeyLineHeight: 13.75,
  metricKeyFontWeight: "500" as const,
} as const;
