/** Паритет `.wholesale-price-modal__*` в `WholesalePriceModal.css`. */
export const WHOLESALE_PRICE_SHEET_LAYOUT = {
  maxWidth: 480,
  borderTopRadius: 32,
  headerPaddingTop: 16,
  headerPaddingHorizontal: 16,
  headerPaddingBottom: 12,
  titleFontSize: 18,
  titleLineHeight: 24.3,
  closeFontSize: 15,
  bodyPadding: 16,
  bodyGap: 13.6,
  hintFontSize: 14.4,
  hintLineHeight: 20.16,
  fieldGap: 5.6,
  labelFontSize: 13.6,
  inputMinHeight: 44,
  inputPaddingVertical: 10.4,
  inputPaddingHorizontal: 12,
  inputBorderRadius: 10,
  inputFontSize: 16,
  footerPaddingVertical: 12,
  footerPaddingHorizontal: 16,
  promoAppliedPaddingVertical: 14.4,
  promoAppliedPaddingHorizontal: 16,
  promoAppliedBorderRadius: 12,
  promoAppliedLabelFontSize: 15.2,
  promoAppliedPercentPaddingVertical: 5.6,
  promoAppliedPercentPaddingHorizontal: 11.2,
  promoAppliedPercentFontSize: 16.8,
  errorFontSize: 14.4,
} as const;
