/**
 * Статичные подписи интерфейса, сгруппированные по темам.
 * Реэкспорт-barrel: содержимое разнесено по ./copy/*.js, чтобы копирайт
 * редких/админских экранов не попадал в бандл главной страницы.
 * Импортируй именованные консты отсюда, как и раньше.
 */

export {
  COMMON_UI,
  APP_RUNTIME_UI,
  APP_PORTRAIT_LOCK_UI,
  FORMAT_BOOLEAN_RU,
  API_CLIENT_UI,
  REGION_UI,
  COOKIE_NOTICE_UI,
  EMAIL_VERIFICATION_UI,
  APP_INTRO_UI,
  IMAGE_URL_FIELD_UI,
  SQUARE_IMAGE_CROP_UI,
  INTRO_VIDEO_UPLOAD_UI,
  VIDEO_URL_FIELD_UI,
  PRODUCT_PREVIEW_VIDEO_UI,
} from "./copy/common.js";
export {
  HOME_PAGE_UI,
  PRODUCT_CATEGORY_DISPLAY_UI,
  PRODUCT_CARD_UI,
  ADD_TO_CART_UI,
  PRODUCT_SIMILAR_UI,
  PRODUCT_COMPARE_UI,
  PRODUCT_SALE_UI,
  PRODUCT_SELLER_PREVIEW_UI,
  PRODUCT_RENTAL_UI,
  PRODUCT_WISHLIST_UI,
  WISHLIST_TOGGLE_UI,
  SITE_HEADER_BANNER_UI,
  RAFFLE_FEATURED_CAROUSEL_UI,
  RAFFLE_FEATURED_BANNER_UI,
  RAFFLE_PRIZE_MEDIA_UI,
  CURATED_PRODUCT_COMPACT_CARD_UI,
} from "./copy/catalog.js";
export {
  HEADER_CART_BUTTON_UI,
  HEADER_PLACE_PRODUCT_BUTTON_UI,
  HEADER_PROFILE_BUTTON_UI,
  HEADER_USERS_BUTTON_UI,
  HEADER_WISHLIST_BUTTON_UI,
  HEADER_NOTIFICATIONS_BUTTON_UI,
  USER_SEARCH_UI,
  USER_SEARCH_INPUT_UI,
  PRODUCT_SEARCH_INPUT_UI,
} from "./copy/header-search.js";
export {
  PRODUCT_DETAILS_MODAL_UI,
  PRODUCT_REVIEW_UI,
  PRODUCT_QA_UI,
  PRODUCT_PRICE_OFFER_UI,
  PRODUCT_PROMO_CODE_UI,
  PRODUCT_WHOLESALE_UI,
  PRODUCT_BUY_N_FREE_UI,
  PRODUCT_BADGE_EXPLAIN_UI,
} from "./copy/product-detail.js";
export {
  CREATE_PRODUCT_MODAL_UI,
  PRODUCT_CATEGORY_TREE_UI,
  CREATE_RAFFLE_MODAL_UI,
  SELLER_PRODUCTS_LIMIT_MODAL_UI,
  ACCOUNT_REQUIREMENT_MODAL_UI,
} from "./copy/product-create.js";
export { PRODUCT_FLASH_SALE_UI } from "./copy/product-flash-sale.js";
export {
  SELLER_PRODUCTS_PAGE_UI,
  SELLER_SHELF_UI,
  PRODUCT_PROMOTIONS_STAFF_PAGE_UI,
  PRODUCT_PROMOTION_UI,
  PRODUCT_MANAGE_TOGGLE_DISPLAY_ADMIN_PAGE_UI,
  PRODUCT_MANAGE_TOGGLE_DISPLAY_ADMIN_UI,
} from "./copy/product-manage.js";
export {
  CART_PAGE_UI,
  CART_AUCTION_UI,
  ADDRESS_STRUCTURED_UI,
  ADDRESS_DELIVERY_UI,
  USER_SAVED_ADDRESSES_UI,
  CHECKOUT_FORM_UI,
  PRODUCT_PICKUP_UI,
} from "./copy/cart-checkout.js";
export {
  ORDER_CARD_UI,
  MY_ORDERS_PAGE_UI,
  MY_SALES_PAGE_UI,
  ADMIN_ORDERS_PAGE_UI,
} from "./copy/orders.js";
export { COURIER_UI, COURIER_MODERATION_UI } from "./copy/courier.js";
export {
  AUCTION_PAGE_UI,
} from "./copy/auction.js";
export {
  AUTH_UI,
  LOGIN_MODAL_UI,
  REGISTER_MODAL_UI,
} from "./copy/auth.js";
export {
  MY_PROFILE_PAGE_UI,
  THEME_SETTINGS_UI,
  WEB_PUSH_SETTINGS_UI,
  EDIT_PROFILE_MODAL_UI,
  ADDRESS_PROMPT_UI,
  PROFILE_IMAGE_FOCUS_EDITOR_UI,
  USER_PROFILE_COPY,
  DELETE_ACCOUNT_UI,
  USER_PREMIUM_UI,
  USER_DATA_CONFIRMED_UI,
  formatUserProfileRatingLine,
  formatUserProfileRatingValue,
  formatUserProfileRatingVotesLabel,
} from "./copy/profile.js";
export {
  USER_VOTE_RATING_UI,
  USER_DETAILS_MODAL_UI,
  USER_DETAILS_PAGE_UI,
  USER_PROFILE_PURCHASES_UI,
  USER_PROFILE_PRODUCTS_UI,
  USER_STORY_UI,
  USER_FOLLOW_BUTTON_UI,
  USER_BLOCK_BUTTON_UI,
} from "./copy/profile-view.js";
export {
  LOYALTY_POINTS_PAGE_UI,
  PARTNER_PROGRAM_PAGE_UI,
  AFFILIATE_LISTINGS_PAGE_UI,
  PREMIUM_PAGE_UI,
  SUBSCRIPTIONS_PAGE_UI,
} from "./copy/loyalty-premium.js";
export {
  WISHLIST_PAGE_UI,
  NOTIFICATIONS_PAGE_UI,
  IN_APP_NOTIFICATIONS_UI,
} from "./copy/wishlist-notifications.js";
export {
  RAFFLE_MANAGE_UI,
  RAFFLE_SELLER_PANEL_UI,
  RAFFLES_STAFF_PAGE_UI,
  USERS_LOYALTY_RAFFLE_ADMIN_UI,
  RAFFLE_PRODUCTS_PAGE_UI,
  RAFFLE_ADVERTISING_PAGE_UI,
} from "./copy/raffle.js";
export {
  INSTALLMENT_UI,
} from "./copy/installment.js";
export {
  DATA_CONFIRMATION_PAGE_UI,
  USER_DATA_CONFIRMATION_PROFILE_PAGE_UI,
  DATA_CONFIRMATION_MODAL_UI,
  PRODUCT_REPORT_MODAL_UI,
} from "./copy/data-confirmation.js";
export {
  INTRO_AD_MODERATION_PAGE_UI,
  ADVERTISING_PAGE_UI,
  INTRO_AD_PAGE_UI,
  SITE_HEADER_BANNER_CAMPAIGN_PAGE_UI,
  SITE_HEADER_BANNER_CAMPAIGN_MODERATION_PAGE_UI,
  SELLER_PERSONAL_CATEGORY_PAGE_UI,
  SELLER_PERSONAL_CATEGORY_MODERATION_PAGE_UI,
  PRODUCT_MODERATION_PAGE_UI,
  PRODUCT_REPORTS_PAGE_UI,
} from "./copy/moderation-advertising.js";
export {
  USERS_PAGE_UI,
  USERS_PODIUM_UI,
  USERS_MONTHLY_LOYALTY_LOADBAR_UI,
  ADMIN_EDIT_USER_UI,
  USER_LIST_ROW_UI,
  ADMIN_PANEL_UI,
  POPULAR_PRODUCTS_ADMIN_PAGE_UI,
  POPULAR_CATEGORIES_ADMIN_PAGE_UI,
  ADMIN_ANALYTICS_PAGE_UI,
  STAFF_AUDIT_LOG_ADMIN_PAGE_UI,
  STAFF_BROADCAST_NOTIFICATIONS_ADMIN_PAGE_UI,
  SEARCH_SYNONYMS_ADMIN_PAGE_UI,
  CATEGORY_TREE_ADMIN_PAGE_UI,
  APP_INTRO_ADMIN_PAGE_UI,
  SITE_HEADER_BANNER_ADMIN_PAGE_UI,
  PRODUCT_BADGE_EXPLAIN_ADMIN_PAGE_UI,
  PRODUCT_BADGE_EXPLAIN_ADMIN_UI,
} from "./copy/admin.js";
export {
  FAQ_UI,
  LEGAL_UI,
} from "./copy/faq-legal.js";
