export const PRODUCT_MODERATION_PENDING = "pending";
export const PRODUCT_MODERATION_APPROVED = "approved";
export const PRODUCT_MODERATION_REJECTED = "rejected";

/** @type {readonly [typeof PRODUCT_MODERATION_PENDING, typeof PRODUCT_MODERATION_APPROVED, typeof PRODUCT_MODERATION_REJECTED]} */
export const PRODUCT_MODERATION_STATUSES = [
  PRODUCT_MODERATION_PENDING,
  PRODUCT_MODERATION_APPROVED,
  PRODUCT_MODERATION_REJECTED,
];
