export const INSTALLMENT_MODERATION_PENDING = "pending";
export const INSTALLMENT_MODERATION_APPROVED = "approved";
export const INSTALLMENT_MODERATION_REJECTED = "rejected";

export const INSTALLMENT_CONTRACT_STATUS_PENDING_FIRST_PAYMENT =
  "pending_first_payment";
export const INSTALLMENT_CONTRACT_STATUS_ACTIVE = "active";
export const INSTALLMENT_CONTRACT_STATUS_COMPLETED = "completed";
export const INSTALLMENT_CONTRACT_STATUS_DEFAULTED = "defaulted";
export const INSTALLMENT_CONTRACT_STATUS_CANCELLED = "cancelled";

export const INSTALLMENT_SALES_LIST_FILTER_IN_PROGRESS = "in_progress";

export const INSTALLMENT_SALES_LIST_FILTERS = [
  INSTALLMENT_SALES_LIST_FILTER_IN_PROGRESS,
  INSTALLMENT_CONTRACT_STATUS_COMPLETED,
  INSTALLMENT_CONTRACT_STATUS_DEFAULTED,
  INSTALLMENT_CONTRACT_STATUS_CANCELLED,
];

export const INSTALLMENT_PAYMENT_STATUS_SCHEDULED = "scheduled";
export const INSTALLMENT_PAYMENT_STATUS_DUE = "due";
export const INSTALLMENT_PAYMENT_STATUS_OVERDUE = "overdue";
export const INSTALLMENT_PAYMENT_STATUS_PENDING_CONFIRMATION = "pending_confirmation";
export const INSTALLMENT_PAYMENT_STATUS_PAID = "paid";

export const INSTALLMENT_PLANS_MAX = 5;
export const INSTALLMENT_PLAN_TITLE_MAX_LENGTH = 80;
export const INSTALLMENT_MONTHS_MIN = 2;
export const INSTALLMENT_MONTHS_MAX = 24;
export const INSTALLMENT_MONTHLY_PAYMENT_MIN_RUB = 100;
