export const CURATED_PRODUCT_LIST_HOME_VISIBLE_CARD_MAX = 10;

export const CURATED_PRODUCT_LIST_HOME_CARD_GAP_PX = 12;

export const CURATED_PRODUCT_LIST_HOME_CARD_MIN_WIDTH_PX = 86;

export const CURATED_PRODUCT_LIST_HOME_CARD_MAX_WIDTH_PX = 168;
