/** SSOT: `contract/src/productReview.js`. */
export {
  PRODUCT_REVIEW_TEXT_MAX_LENGTH,
  PRODUCT_REVIEW_RATING_MIN,
  PRODUCT_REVIEW_RATING_MAX,
  PRODUCT_REVIEW_LIMIT_DEFAULT as PRODUCT_REVIEW_PAGE_LIMIT,
} from "@molha/api-contract";
