export const PRODUCT_PROMOTION_MODAL_TAB_PROMOTION = "promotion";
export const PRODUCT_PROMOTION_MODAL_TAB_MANAGE = "manage";

export const PRODUCT_PROMOTION_MODAL_DEFAULT_TAB = PRODUCT_PROMOTION_MODAL_TAB_PROMOTION;

export type ProductPromotionModalTabId =
  | typeof PRODUCT_PROMOTION_MODAL_TAB_PROMOTION
  | typeof PRODUCT_PROMOTION_MODAL_TAB_MANAGE;
