import {
  ADMIN_ANALYTICS_DEFINITIONS_VERSION,
  ADMIN_ANALYTICS_PERIOD_7D,
  ADMIN_ANALYTICS_PERIOD_30D,
  ADMIN_ANALYTICS_PERIOD_ALL,
  ADMIN_ANALYTICS_PERIOD_TODAY,
  ADMIN_ANALYTICS_PERIODS,
} from "@molha/api-contract";

export {
  ADMIN_ANALYTICS_DEFINITIONS_VERSION,
  ADMIN_ANALYTICS_PERIOD_7D,
  ADMIN_ANALYTICS_PERIOD_30D,
  ADMIN_ANALYTICS_PERIOD_ALL,
  ADMIN_ANALYTICS_PERIOD_TODAY,
  ADMIN_ANALYTICS_PERIODS,
};

/** Nightly reconciliation (~24h). Idempotent day-key в сервисе. */
export const ANALYTICS_RECONCILIATION_CRON_INTERVAL_MS = 24 * 60 * 60 * 1000;

export const ANALYTICS_RECONCILIATION_MISMATCH_SAMPLE_LIMIT = 25;
