export const PRODUCT_CHARACTERISTICS_MAX_ITEMS = 10;
export const PRODUCT_CHARACTERISTIC_KEY_MAX_CHARS = 50;
export const PRODUCT_CHARACTERISTIC_VALUE_MAX_CHARS = 200;

export const PRODUCT_CHARACTERISTIC_EMPTY_PAIR_MESSAGE =
  "Пара характеристики: укажите и ключ, и значение";
