/** Статус цены относительно рынка (блок 2 на деталях). */
export const PRODUCT_PRICE_MARKET_STATUS_ABOVE = "above_market";
export const PRODUCT_PRICE_MARKET_STATUS_AT = "at_market";
export const PRODUCT_PRICE_MARKET_STATUS_BELOW = "below_market";
export const PRODUCT_PRICE_MARKET_STATUS_UNKNOWN = "unknown";

export const PRODUCT_PRICE_MARKET_STATUS_VALUES = [
  PRODUCT_PRICE_MARKET_STATUS_ABOVE,
  PRODUCT_PRICE_MARKET_STATUS_AT,
  PRODUCT_PRICE_MARKET_STATUS_BELOW,
  PRODUCT_PRICE_MARKET_STATUS_UNKNOWN,
];

export const PRODUCT_PRICE_MARKET_STATUS_DEFAULT = PRODUCT_PRICE_MARKET_STATUS_UNKNOWN;
