export const PRODUCT_MODERATION_PENDING = "pending";
export const PRODUCT_MODERATION_APPROVED = "approved";
export const PRODUCT_MODERATION_REJECTED = "rejected";

export const PRODUCT_MODERATION_STATUSES = [
  PRODUCT_MODERATION_PENDING,
  PRODUCT_MODERATION_APPROVED,
  PRODUCT_MODERATION_REJECTED,
];

/** Значения query `moderationStatus` для GET /product/my (фильтр «Мои товары»). */
export const MY_PRODUCTS_MODERATION_FILTER_VALUES = [
  PRODUCT_MODERATION_PENDING,
  PRODUCT_MODERATION_REJECTED,
];

export const PRODUCT_MODERATION_COMMENT_MAX_LENGTH = 2000;
