export const PRODUCT_MODERATION_PENDING = "pending";
export const PRODUCT_MODERATION_APPROVED = "approved";
export const PRODUCT_MODERATION_REJECTED = "rejected";

export const PRODUCT_MODERATION_STATUSES = [
  PRODUCT_MODERATION_PENDING,
  PRODUCT_MODERATION_APPROVED,
  PRODUCT_MODERATION_REJECTED,
];

/** Query `moderationStatus` для GET /product/my — единый list-фильтр. */
export const MY_PRODUCTS_LIST_FILTER_PENDING = PRODUCT_MODERATION_PENDING;
export const MY_PRODUCTS_LIST_FILTER_APPROVED = PRODUCT_MODERATION_APPROVED;
export const MY_PRODUCTS_LIST_FILTER_REJECTED = PRODUCT_MODERATION_REJECTED;
export const MY_PRODUCTS_LIST_FILTER_HIDDEN = "hidden";
export const MY_PRODUCTS_LIST_FILTER_PROMOTED = "promoted";
export const MY_PRODUCTS_LIST_FILTER_NOT_PROMOTED = "not_promoted";

export const MY_PRODUCTS_LIST_FILTER_VALUES = [
  MY_PRODUCTS_LIST_FILTER_PENDING,
  MY_PRODUCTS_LIST_FILTER_APPROVED,
  MY_PRODUCTS_LIST_FILTER_REJECTED,
  MY_PRODUCTS_LIST_FILTER_HIDDEN,
  MY_PRODUCTS_LIST_FILTER_PROMOTED,
  MY_PRODUCTS_LIST_FILTER_NOT_PROMOTED,
];

/** @deprecated alias */
export const MY_PRODUCTS_MODERATION_FILTER_VALUES = MY_PRODUCTS_LIST_FILTER_VALUES;

export const PRODUCT_MODERATION_COMMENT_MAX_LENGTH = 2000;

export const IN_APP_NOTIFICATION_KIND_MODERATION_TRUST_GRANTED =
  "product_moderation_trust_granted";
export const IN_APP_NOTIFICATION_KIND_MODERATION_TRUST_REVOKED =
  "product_moderation_trust_revoked";

export const IN_APP_NOTIFICATION_MESSAGE_MODERATION_TRUST_GRANTED =
  "Ваши товары публикуются без проверки: новая карточка попадает в каталог сразу.";
export const IN_APP_NOTIFICATION_MESSAGE_MODERATION_TRUST_REVOKED =
  "Публикация без проверки отключена: новые товары снова проходят модерацию.";
