/** SSOT: `contract/src/productWrite.js`. */
export {
  PRODUCT_IMAGE_URLS_MAX,
  PRODUCT_NAME_MIN_LENGTH,
  PRODUCT_NAME_MAX_LENGTH,
  PRODUCT_DESCRIPTION_MIN_CHARS,
  PRODUCT_DESCRIPTION_MAX_CHARS,
  PRODUCT_PRICE_RUB_MAX,
  PRODUCT_CATEGORY_VALUES,
  SELLER_PRODUCTS_LIMIT_REGULAR,
  SELLER_PRODUCTS_LIMIT_PREMIUM,
  SELLER_PRODUCTS_LIMIT_ERROR_MESSAGE,
} from "@molha/api-contract";

export const PRODUCT_PRICE_RUB_MAX_ERROR_MESSAGE =
  "Цена не может превышать 999 999 999 ₽";
