export const PROFILE_IMAGE_FOCUS_MIN = 0;
export const PROFILE_IMAGE_FOCUS_MAX = 100;
export const PROFILE_IMAGE_FOCUS_DEFAULT = 50;

export const DEFAULT_USER_AVATAR_FOCUS = {
  x: PROFILE_IMAGE_FOCUS_DEFAULT,
  y: PROFILE_IMAGE_FOCUS_DEFAULT,
};

export const DEFAULT_USER_BACKGROUND_FOCUS = {
  x: PROFILE_IMAGE_FOCUS_DEFAULT,
  y: PROFILE_IMAGE_FOCUS_DEFAULT,
};

export const DEFAULT_RAFFLE_PRIZE_IMAGE_FOCUS = {
  x: PROFILE_IMAGE_FOCUS_DEFAULT,
  y: PROFILE_IMAGE_FOCUS_DEFAULT,
};
