export const SITE_HEADER_BANNER_CAMPAIGN_STATUS_PENDING = "pending";
export const SITE_HEADER_BANNER_CAMPAIGN_STATUS_ACTIVE = "active";
export const SITE_HEADER_BANNER_CAMPAIGN_STATUS_REJECTED = "rejected";
export const SITE_HEADER_BANNER_CAMPAIGN_STATUS_EXPIRED = "expired";
export const SITE_HEADER_BANNER_CAMPAIGN_STATUS_CANCELLED = "cancelled";

export const SITE_HEADER_BANNER_CAMPAIGN_STATUSES = [
  SITE_HEADER_BANNER_CAMPAIGN_STATUS_PENDING,
  SITE_HEADER_BANNER_CAMPAIGN_STATUS_ACTIVE,
  SITE_HEADER_BANNER_CAMPAIGN_STATUS_REJECTED,
  SITE_HEADER_BANNER_CAMPAIGN_STATUS_EXPIRED,
  SITE_HEADER_BANNER_CAMPAIGN_STATUS_CANCELLED,
];

export const SITE_HEADER_BANNER_CAMPAIGN_OPEN_STATUSES = [
  SITE_HEADER_BANNER_CAMPAIGN_STATUS_PENDING,
  SITE_HEADER_BANNER_CAMPAIGN_STATUS_ACTIVE,
];

export const SITE_HEADER_BANNER_CAMPAIGN_PRICE_POINTS = 7_000;
export const SITE_HEADER_BANNER_CAMPAIGN_DURATION_MS = 7 * 24 * 60 * 60 * 1000;
export const SITE_HEADER_BANNER_CAMPAIGN_PAID_SLOT_LIMIT = 3;
export const SITE_HEADER_BANNER_CAMPAIGN_CRON_INTERVAL_MS = 5 * 60 * 1000;

export const SITE_HEADER_BANNER_CAMPAIGN_NOTIFICATION_KIND_APPROVED =
  "site_header_banner_campaign_approved";
export const SITE_HEADER_BANNER_CAMPAIGN_NOTIFICATION_KIND_REJECTED =
  "site_header_banner_campaign_rejected";
export const SITE_HEADER_BANNER_CAMPAIGN_NOTIFICATION_KIND_EXPIRED =
  "site_header_banner_campaign_expired";
export const SITE_HEADER_BANNER_CAMPAIGN_NOTIFICATION_KIND_CANCELLED_BY_STAFF =
  "site_header_banner_campaign_cancelled_by_staff";
