export {
  INTRO_UPLOAD_VIDEO_MAX_MB,
  INTRO_UPLOAD_VIDEO_MAX_BYTES,
  STORY_UPLOAD_VIDEO_MAX_MB,
  STORY_UPLOAD_VIDEO_MAX_BYTES,
  UPLOAD_IMAGE_MAX_BYTES,
  UPLOAD_IMAGE_MIME_TYPES,
  UPLOAD_VIDEO_MAX_MB,
  UPLOAD_VIDEO_MAX_BYTES,
  UPLOAD_VIDEO_MIME_TYPES,
  UPLOAD_VIDEO_EXTENSIONS,
} from "@molha/api-contract";
