export const USERS_LOYALTY_RAFFLE_SETTINGS_KEY = "default";
export const USERS_LOYALTY_RAFFLE_DESCRIPTION_MAX_LENGTH = 2000;
export const USERS_LOYALTY_RAFFLE_GOAL_MIN = 1;
export const USERS_LOYALTY_RAFFLE_GOAL_MAX = 10_000_000;
export const USERS_LOYALTY_RAFFLE_GOAL_DEFAULT = 50_000;
