export const USER_DATA_CONFIRMATION_STATUS_PENDING = 'pending';
export const USER_DATA_CONFIRMATION_STATUS_APPROVED = 'approved';
export const USER_DATA_CONFIRMATION_STATUS_REJECTED = 'rejected';

export const USER_DATA_CONFIRMATION_STATUSES = [
    USER_DATA_CONFIRMATION_STATUS_PENDING,
    USER_DATA_CONFIRMATION_STATUS_APPROVED,
    USER_DATA_CONFIRMATION_STATUS_REJECTED,
];

export const USER_DATA_CONFIRMATION_RESOLUTION_APPROVE = 'approve';
export const USER_DATA_CONFIRMATION_RESOLUTION_REJECT = 'reject';

export const USER_DATA_CONFIRMATION_RESOLUTIONS = [
    USER_DATA_CONFIRMATION_RESOLUTION_APPROVE,
    USER_DATA_CONFIRMATION_RESOLUTION_REJECT,
];

/** Макс. заявок с одного аккаунта за час. */
export const USER_DATA_CONFIRMATION_RATE_LIMIT_PER_HOUR = 1;

export const USER_DATA_CONFIRMATION_ALREADY_PENDING_MESSAGE =
    'Заявка уже на рассмотрении';

export const USER_DATA_CONFIRMATION_ALREADY_CONFIRMED_MESSAGE =
    'Данные уже подтверждены';

export const IN_APP_NOTIFICATION_KIND_DATA_CONFIRMATION_APPROVED =
    'data_confirmation_approved';
export const IN_APP_NOTIFICATION_KIND_DATA_CONFIRMATION_REJECTED =
    'data_confirmation_rejected';

export const IN_APP_NOTIFICATION_MESSAGE_DATA_CONFIRMATION_APPROVED =
    'Ваши данные подтверждены';
export const IN_APP_NOTIFICATION_MESSAGE_DATA_CONFIRMATION_REJECTED =
    'Заявка отклонена';

export const USER_DATA_CONFIRMATION_AUTO_REJECT_STAFF_NOTE =
    'Подтверждение снято администратором';

export const USER_DATA_CONFIRMATION_STAFF_NOTE_MIN_WORDS = 3;
