import { semanticColors } from "@/shared/theme/semanticColors";

/** Синхронизировано с client/src/shared/styles/designTokens.css */
export const RAFFLE_FEATURED_PALETTE = {
  accentPurple: semanticColors.accent,
  accentPurpleSoft: semanticColors.accentSoft,
  accentPurpleText: semanticColors.accent,
  premiumPurpleMuted: semanticColors.accentSoft,
  premiumPurpleLight: semanticColors.accent,
  accentPinkSurface: semanticColors.accentSoft,
  accentPinkLilac: semanticColors.accentSoft,
  accentPink: semanticColors.accent,
  accentPinkDeep: semanticColors.accent,
  accentPinkSoft: semanticColors.accentSoft,
  surface: semanticColors.onContrast,
  success: semanticColors.success,
  successDeep: semanticColors.successText,
  successLight: semanticColors.successSurface,
  successVivid: semanticColors.success,
  successPale: semanticColors.successSurface,
  successMuted: semanticColors.successText,
  successSurface: semanticColors.successSurface,
  successSoft: semanticColors.successSurface,
  successLightBorder: semanticColors.successSurface,
  dangerAccent: semanticColors.danger,
  dangerSoft: semanticColors.dangerSurface,
  dangerText: semanticColors.dangerText,
  warning: semanticColors.warning,
  warningPeach: semanticColors.warningSurface,
  warningBrownDeep: semanticColors.warningText,
  onContrast: semanticColors.onContrast,
  black: semanticColors.ink,
  shadowPurple: `${semanticColors.accent}1f`,
  shadowSuccess: `${semanticColors.success}1f`,
  progressTrack: `${semanticColors.accent}1f`,
  progressTrackCompleted: `${semanticColors.success}29`,
  manageDivider: `${semanticColors.accent}2e`,
  manageDividerCompleted: `${semanticColors.success}33`,
  overlayMidnight: semanticColors.overlayStrong,
} as const;
