/** Паритет client `RaffleProductsPage.css`. */
export const RAFFLE_PRODUCTS_PAGE_LAYOUT = {
  mediaHeight: 300,
  mediaHeightWide: 342,
  mediaRadius: 22,
  headerRadius: 20,
  progressRadius: 18,
  statRadius: 14,
  wideBreakpoint: 900,
  swipeDotSize: 8,
  swipeDotsGap: 6,
  swipeDotsBottom: 12,
  summaryLayoutWideGap: 14,
  mediaMarginBottom: 12,
  mediaMarginBottomWide: 8,
  headerMarginBottom: 12,
  headerPaddingWideVertical: 13,
  headerPaddingWideHorizontal: 14,
  summarySideHeaderMarginTopWide: 16,
  progressMarginBottom: 16,
  progressGapWide: 7,
  progressPaddingWideVertical: 10,
  progressPaddingWideHorizontal: 11,
  statsGapWide: 6,
  statPaddingWideVertical: 7,
  statPaddingWideHorizontal: 6,
  productsBlockMarginTop: 10,
  manageDesktopMarginBottom: 14,
  descriptionMarginBottom: 12,
  descriptionDesktopMarginTop: 9,
} as const;
