export {
  APP_INTRO_FADE_OUT_MS,
  APP_INTRO_MAX_MS,
  APP_INTRO_MIN_MS,
  APP_INTRO_POSTER,
  APP_INTRO_SEEN_STORAGE_KEY,
  APP_INTRO_VIDEO_MP4,
  APP_INTRO_VIDEO_WEBM,
} from "../../../shared/config/appIntroConstants.js";
