// Автосгенерировано из appUiCopy.js: домен «auth».
// Реэкспортируется через ../appUiCopy.js — импортируй оттуда, как раньше.

/** Full-screen auth (parity with mobile AUTH_UI) */
export const AUTH_UI = {
  LOGIN_TITLE: "Вход",
  LOGIN_SUBTITLE: "Войдите, чтобы продолжить покупки",
  REGISTER_TITLE: "Регистрация",
  REGISTER_SUBTITLE: "Создайте аккаунт за пару минут",
  EMAIL_LABEL: "Email",
  EMAIL_PLACEHOLDER: "you@example.com",
  PASSWORD_LABEL: "Пароль",
  PASSWORD_PLACEHOLDER: "••••••••",
  PASSWORD_CONFIRM_LABEL: "Повторите пароль",
  PASSWORD_CONFIRM_PLACEHOLDER: "••••••••",
  SHOW_PASSWORD_ARIA: "Показать пароль",
  HIDE_PASSWORD_ARIA: "Скрыть пароль",
  USER_NAME_LABEL: "Имя пользователя",
  USER_NAME_PLACEHOLDER: "username",
  LOGIN_BUTTON: "Войти",
  REGISTER_BUTTON: "Зарегистрироваться",
  LOGOUT_BUTTON: "Выйти",
  GO_TO_REGISTER: "Создать аккаунт",
  GO_TO_LOGIN: "Уже есть аккаунт? Войти",
  BACK_BUTTON: "Назад",
  GUEST_STATUS: "Вы не вошли в аккаунт",
  REGISTER_TERMS_CONSENT_PREFIX: "Я принимаю ",
  REGISTER_TERMS_LINK: "Пользовательское соглашение",
  REGISTER_TERMS_CONSENT_AND: " и ",
  REGISTER_LISTING_LINK: "Правила размещения товаров",
  REGISTER_PRIVACY_CONSENT_PREFIX: "Я даю ",
  REGISTER_PRIVACY_CONSENT_LINK: "согласие на обработку персональных данных",
  REGISTER_PRIVACY_CONSENT_SUFFIX: " в соответствии с ",
  REGISTER_PRIVACY_LINK: "Политикой конфиденциальности",
  REGISTER_CONSENT_REQUIRED: "Подтвердите согласие с документами для регистрации",
  REGISTER_CODE_TITLE: "Подтвердите почту",
  REGISTER_CODE_SUBTITLE: (email) =>
    `Мы отправили 6-значный код на ${email}. Аккаунт будет создан только после подтверждения почты.`,
  REGISTER_CODE_LABEL: "Код из письма",
  REGISTER_CODE_PLACEHOLDER: "000000",
  REGISTER_CODE_REQUIRED: "Введите 6-значный код из письма",
  REGISTER_CODE_CONFIRM_BUTTON: "Подтвердить почту",
  REGISTER_CODE_RESEND_BUTTON: "Отправить код повторно",
  REGISTER_CODE_BACK_BUTTON: "Изменить данные регистрации",
  GUEST_PROFILE_ACTION_BUTTON: "Перейти",
  PROFILE_TITLE: "Профиль",
  SESSION_CHECK: "Проверка сессии…",
  SESSION_ERROR: "Ошибка сессии",
  FORGOT_PASSWORD_LINK: "Забыли пароль?",
  FORGOT_TITLE: "Восстановление пароля",
  FORGOT_SUBTITLE: "Укажите подтверждённый email или телефон — пришлём код",
  FORGOT_CONFIRM_SUBTITLE: "Введите код и новый пароль",
  FORGOT_DONE_SUBTITLE: "Можно войти с новым паролем",
  FORGOT_DONE_MESSAGE: "Пароль изменён. Войдите с новым паролем.",
  FORGOT_SEND_BUTTON: "Получить код",
  FORGOT_SEND_LOADING: "Отправка…",
  FORGOT_CODE_SENT: "Если аккаунт с этим контактом существует, код отправлен",
  FORGOT_CODE_LABEL_EMAIL: "Код из письма",
  FORGOT_CODE_LABEL_SMS: "Код из SMS",
  FORGOT_CODE_PLACEHOLDER: "000000",
  FORGOT_CODE_LENGTH: 6,
  FORGOT_NEW_PASSWORD_LABEL: "Новый пароль",
  FORGOT_NEW_PASSWORD_CONFIRM_LABEL: "Повторите новый пароль",
  FORGOT_CONFIRM_BUTTON: "Сменить пароль",
  FORGOT_CONFIRM_LOADING: "Сохранение…",
  FORGOT_RESEND_BUTTON: "Отправить код повторно",
  FORGOT_RESEND_LOADING: "Отправка…",
  FORGOT_ERROR_EMAIL_REQUIRED: "Укажите email",
  FORGOT_ERROR_CODE_REQUIRED: "Введите 6-значный код",
  FORGOT_ERROR_PASSWORD_TOO_SHORT: "Пароль должен быть не менее 6 символов",
  FORGOT_ERROR_PASSWORD_MISMATCH: "Пароли не совпадают",
};

/** Модалка входа */
export const LOGIN_MODAL_UI = {
  ARIA_DIALOG: "Вход в аккаунт",
  ARIA_CLOSE_BACKDROP: "Закрыть окно входа",
  TITLE: "Вход",
  CHANNEL_EMAIL: "Email",
  CHANNEL_PHONE: "Телефон",
  LABEL_EMAIL: "Email",
  LABEL_PHONE: "Телефон",
  LABEL_PASSWORD: "Пароль",
  LABEL_CODE: "Код из SMS",
  CODE_PLACEHOLDER: "000000",
  PHONE_METHOD_PASSWORD: "Пароль",
  PHONE_METHOD_SMS: "Код из SMS",
  SEND_CODE: "Получить код",
  SEND_CODE_LOADING: "Отправка…",
  CODE_SENT: "Код отправлен по SMS",
  SHOW_PASSWORD_ARIA: "Показать пароль",
  HIDE_PASSWORD_ARIA: "Скрыть пароль",
  SUBMIT_IDLE: "Войти",
  SUBMIT_LOADING: "Входим…",
  REGISTER_BUTTON: "Зарегистрироваться",
  SUCCESS: "Вы успешно вошли в аккаунт",
  ERROR_GENERIC: "Ошибка при входе",
  ERROR_PHONE_REQUIRED: "Укажите номер телефона",
  ERROR_CODE_REQUIRED: "Введите 6-значный код из SMS",
  SESSION_VERIFY_FALLBACK:
    "Вход выполнен, но сессия не сохранилась. Обновите страницу и войдите снова.",
  PASSWORD_MIN_LENGTH: 6,
  CODE_LENGTH: 6,
};

/** Модалка регистрации */
export const REGISTER_MODAL_UI = {
  ARIA_DIALOG: "Регистрация",
  ARIA_CLOSE_BACKDROP: "Закрыть окно регистрации",
  TITLE: "Регистрация",
  CHANNEL_EMAIL: "Email",
  CHANNEL_PHONE: "Телефон",
  LABEL_EMAIL: "Email",
  LABEL_PHONE: "Телефон",
  LABEL_PASSWORD: "Пароль",
  LABEL_PASSWORD_CONFIRM: "Повторите пароль",
  SHOW_PASSWORD_ARIA: "Показать пароль",
  HIDE_PASSWORD_ARIA: "Скрыть пароль",
  LABEL_USERNAME: "Никнейм",
  USERNAME_HINT:
    "Только a–z и 0–9, без пробелов, 3–30 символов (как одно слово в нижнем регистре).",
  SUBMIT_IDLE: "Зарегистрироваться",
  SUBMIT_LOADING: "Регистрация…",
  ERROR_GENERIC: "Ошибка при регистрации",
  ERROR_REQUIRED_FIELDS: "Заполните обязательные поля",
  CODE_STEP_TEXT: (email) =>
    `Мы отправили 6-значный код на ${email}. Аккаунт будет создан только после подтверждения почты.`,
  CODE_STEP_PHONE_TEXT: (phone) =>
    `Мы отправили 6-значный код на ${phone}. Аккаунт будет создан только после подтверждения SMS.`,
  CODE_STEP_EMAIL_FALLBACK: "ваш email",
  CODE_STEP_PHONE_FALLBACK: "ваш телефон",
  LABEL_CODE: "Код из письма",
  LABEL_CODE_SMS: "Код из SMS",
  CODE_PLACEHOLDER: "000000",
  CODE_REQUIRED: "Введите 6-значный код из письма",
  CODE_REQUIRED_SMS: "Введите 6-значный код из SMS",
  CONFIRM_IDLE: "Подтвердить почту",
  CONFIRM_IDLE_SMS: "Подтвердить телефон",
  CONFIRM_LOADING: "Проверка…",
  RESEND_BUTTON: "Отправить код повторно",
  RESEND_LOADING: "Отправка…",
  RESENT: "Письмо отправлено. Проверьте почту.",
  RESENT_SMS: "Код отправлен по SMS.",
  BACK_TO_FORM: "Изменить данные регистрации",
  ERROR_PASSWORD_MISMATCH: "Пароли не совпадают",
  ERROR_PASSWORD_TOO_SHORT: "Пароль должен быть не менее 6 символов",
  PASSWORD_MIN_LENGTH: 6,
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 30,
};
