// Автосгенерировано из appUiCopy.js: домен «installment».
// Реэкспортируется через ../appUiCopy.js — импортируй оттуда, как раньше.

/** Рассрочка */
export const INSTALLMENT_UI = {
  BADGE: "Рассрочка",
  TAB: "Рассрочка",
  SHORTCUT: "В рассрочку",
  DETAILS_TEASER_TITLE: "Рассрочка",
  /** @param {string} monthlyLabel */
  DETAILS_TEASER_FROM_MONTHLY: (monthlyLabel) => `от ${monthlyLabel} / мес`,
  DETAILS_TEASER_GO: "Оформить сейчас",
  DETAILS_TEASER_ARIA: "Открыть вкладку рассрочки",
  BUYER_HINT: "Оформление рассрочки доступно пользователям с подтверждёнными данными.",
  BUYER_REQUIRES_CONFIRMED:
    "Рассрочка доступна только пользователям с подтверждёнными данными.",
  BUYER_PRODUCT_PRICE_LABEL: "Цена товара",
  BUYER_MARKUP_LABEL: "Переплата",
  PLANS_LABEL: "План рассрочки",
  FIRST_PAYMENT_LATER: "первый платёж позже",
  QUANTITY_LABEL: "Количество",
  /** @param {number} max */
  QUANTITY_AVAILABLE: (max) => `Доступно: ${max}`,
  /** @param {number} max */
  QUANTITY_EXCEEDS_STOCK: (max) => `В наличии только ${max} шт.`,
  MONTHLY_LABEL: "Ежемесячно",
  TOTAL_LABEL: "Итого по договору",
  PAYMENT_METHOD_LABEL: "Способ оплаты",
  SUBMIT: "Оформить рассрочку",
  SUBMITTING: "Оформляем…",
  SELECT_PLAN: "Выберите план рассрочки",
  CONTRACT_SUCCESS: "Рассрочка оформлена. Следите за графиком платежей.",
  ERROR_GENERIC: "Не удалось выполнить действие",
  PASSPORT_SHARE_CONSENT_TITLE: "Согласие на передачу паспортных данных",
  PASSPORT_SHARE_CONSENT_PARAGRAPHS: [
    "Нажимая «Разрешить и оформить», вы даёте отдельное согласие оператору сервиса Gitorg на передачу продавцу выбранного товара ваших паспортных данных, ранее предоставленных при подтверждении аккаунта: фамилия, имя, отчество (при наличии), дата рождения, серия и номер паспорта, сведения о выдаче (кем выдан, дата выдачи, код подразделения), а также фотография с паспортом в руках.",
    "Цель передачи — идентификация покупателя и рассмотрение (исполнение) заявки на покупку товара в рассрочку по этой сделке. Получатель — продавец указанного товара (третье лицо). Передача выполняется однократно в составе заявки на покупку.",
    "Согласие даётся добровольно. Без него оформить покупку в рассрочку нельзя. Отказ («Отмена») не ограничивает иные покупки без рассрочки.",
    "Вы вправе отозвать согласие, обратившись к оператору по контактам из Политики конфиденциальности. Отзыв не отменяет законность передачи, уже совершённой до отзыва. Дальнейшую обработку полученных данных продавец осуществляет самостоятельно в соответствии с законодательством РФ.",
    "Подтверждая действие, вы также подтверждаете, что ознакомлены с Политикой конфиденциальности сервиса.",
  ],
  PASSPORT_SHARE_CONSENT_CANCEL: "Отмена",
  PASSPORT_SHARE_CONSENT_CONFIRM: "Разрешить и оформить",
  PASSPORT_SHARE_SECTION: "Паспорт покупателя",
  PASSPORT_SHARE_SELFIE_SECTION: "Фото с паспортом в руках",
  PASSPORT_SHARE_SELFIE_OPEN: "Открыть фото в полном размере",
  PASSPORT_SHARE_SELFIE_MISSING: "Фото не приложено",
  PASSPORT_SHARE_SELFIE_LOAD_ERROR: "Не удалось загрузить фото",
  MODERATION_PENDING: "Программа на модерации",
  PROGRAM_MODAL_REJECTED_HINT:
    "Программа была отклонена ранее. Исправьте планы и сохраните снова — рассрочка сразу станет доступна покупателям.",
  PROGRAM_MODAL_APPROVED_HINT: "Рассрочка активна — покупатели могут оформить её на этот товар.",
  MODERATION_REJECTED: "Программа отклонена",
  MODERATION_APPROVED: "Рассрочка активна",
  SELLER_TAB_HINT: "Настройте планы в «Изменить товар» → «Продать в рассрочку».",
  PROGRAM_MODAL_TITLE: "Рассрочка на товар",
  PROGRAM_MODAL_PLAN_NUMBER: (n) => `План ${n}`,
  PROGRAM_MODAL_PLAN_TITLE: "Название плана",
  PROGRAM_MODAL_PLAN_TITLE_PLACEHOLDER: "Например: Стандарт",
  PROGRAM_MODAL_ERROR_NO_PLANS: "Добавьте хотя бы один план рассрочки",
  /** @param {number} planNumber */
  PROGRAM_MODAL_ERROR_PLAN_TITLE: (planNumber) =>
    `План ${planNumber}: укажите название`,
  /** @param {number} planNumber @param {number} maxLength */
  PROGRAM_MODAL_ERROR_PLAN_TITLE_MAX: (planNumber, maxLength) =>
    `План ${planNumber}: название не длиннее ${maxLength} символов`,
  /** @param {number} planNumber @param {number} min @param {number} max */
  PROGRAM_MODAL_ERROR_PLAN_MONTHS: (planNumber, min, max) =>
    `План ${planNumber}: срок от ${min} до ${max} мес.`,
  /** @param {number} planNumber @param {number} minRub */
  PROGRAM_MODAL_ERROR_PLAN_MONTHLY: (planNumber, minRub) =>
    `План ${planNumber}: минимальный платёж ${minRub} ₽`,
  PROGRAM_MODAL_MONTHS: "Месяцев",
  PROGRAM_MODAL_MARKUP_PERCENT: "Надбавка, %",
  PROGRAM_MODAL_MONTHLY: "Платёж, ₽",
  PROGRAM_MODAL_PLAN_ORIGINAL_PRICE: (formatted) => `Цена товара: ${formatted}`,
  PROGRAM_MODAL_PLAN_MARKUP: (rubFormatted, percent) =>
    `Надбавка: +${rubFormatted} (+${percent}%)`,
  PROGRAM_MODAL_PLAN_TOTAL: (formatted) => `Итого ${formatted}`,
  PROGRAM_MODAL_FIRST_NOW: "Первый платёж сразу",
  PROGRAM_MODAL_ADD_PLAN: "Добавить план",
  PROGRAM_MODAL_REMOVE_PLAN: "Удалить",
  PROGRAM_MODAL_SAVE: "Сохранить",
  PROGRAM_MODAL_SAVING: "Сохраняем…",
  PROGRAM_MODAL_MAX_PLANS: (max) => `Не больше ${max} планов`,
  PROGRAM_MODAL_SUCCESS: "Программа сохранена и активна",
  OVERDUE_BADGE: "Просрочка",
  CONTRACT_PRODUCT: "Товар",
  SELLER_LABEL: "Продавец",
  BUYER_LABEL: "Покупатель",
  BUYERS_LABEL: "Покупатели",
  BUYER_PROFILE_ARIA: (buyerName) => `Профиль покупателя: ${buyerName}`,
  CONTRACT_PLAN: "План",
  CONTRACT_STATUS: "Статус",
  CONTRACT_PAID: "Оплачено",
  CONTRACT_REMAINING: "Осталось",
  CONTRACT_DAYS_LEFT: (days) => `Дней до конца: ${days}`,
  PAYMENTS_HEADING: "График платежей",
  PAYMENTS_FOCUS_HEADING: "Сейчас",
  /** @param {number} count */
  PAYMENTS_UPCOMING_SUMMARY: (count) => `Запланировано · ${count}`,
  /** @param {number} count */
  PAYMENTS_HISTORY_SUMMARY: (count) => `Оплачено · ${count}`,
  PAYMENT_DUE: "Срок",
  PAYMENT_AMOUNT: "Сумма",
  MARK_PAID: "Я оплатил",
  CONFIRM_PAYMENT: "Подтвердить оплату",
  REJECT_PAYMENT: "Отклонить оплату",
  REJECT_EARLY_PAYOFF: "Отклонить досрочное погашение",
  EARLY_PAYOFF: "Досрочное погашение",
  CANCEL_EARLY_PAYOFF: "Отменить досрочное погашение",
  CONFIRM_EARLY_PAYOFF: "Подтвердить досрочное погашение",
  OPEN_DISPUTE: "Открыть спор",
  DISPUTE_REASON_PLACEHOLDER: "Причина спора…",
  SEND_MESSAGE: "Написать продавцу",
  MESSAGE_PLACEHOLDER: "Сообщение…",
  ACTION_PENDING: "Сохраняем…",
  PAYMENTS_PAGE_TITLE: "Покупки - Рассрочка",
  /** @param {number} count */
  COUNT_CONTRACTS: (count) => `${count} договоров`,
  /** @param {number} count */
  COUNT_PROGRAMS: (count) => `${count} программ`,
  /** @param {number} count */
  COUNT_DISPUTES: (count) => `${count} споров`,
  PAYMENTS_PAGE_LOADING: "Загрузка рассрочек…",
  PAYMENTS_PAGE_EMPTY: "У вас пока нет рассрочек.",
  PAYMENTS_PAGE_EMPTY_BY_FILTER: "По выбранному статусу рассрочек нет.",
  /** @param {number} shown @param {number} total */
  COUNT_FILTERED: (shown, total) => `${shown} из ${total}`,
  PAYMENTS_OVERVIEW_ACTIVE: "Активные",
  PAYMENTS_OVERVIEW_ATTENTION: "Нужно действие",
  PAYMENTS_OVERVIEW_REMAINING: "Осталось всего",
  PAYMENTS_EXPAND_ALL: "Развернуть все",
  PAYMENTS_COLLAPSE_ALL: "Свернуть все",
  PAYMENTS_REFRESH: "Обновить",
  /** @param {string} amount @param {string} date */
  PAYMENTS_NEXT_DUE: (amount, date) => `След. платёж: ${amount} · ${date}`,
  PAYMENTS_ATTENTION_FILTER_HINT: "Показаны договоры, где нужно ваше действие",
  /** @param {boolean} expanded */
  PAYMENTS_EXPAND_TOGGLE: (expanded) => (expanded ? "Свернуть" : "Развернуть"),
  SALES_PAGE_TITLE: "Продажи - Рассрочка",
  SALES_PAGE_LOADING: "Загрузка продаж…",
  SALES_PAGE_EMPTY: "Продаж в рассрочку пока нет.",
  SALES_PAGE_EMPTY_BY_FILTER: "По выбранному статусу продаж нет.",
  SALES_OVERVIEW_REMAINING: "К получению",
  SALES_ATTENTION_FILTER_HINT: "Показаны продажи, где нужно подтвердить оплату",
  SALES_NEXT_ACTION_EARLY_PAYOFF: "Досрочное погашение — ждёт подтверждения",
  CONTRACT_STATUS_FILTER_LABEL: "Статус",
  CONTRACT_STATUS_FILTER_ALL: "Все",
  CONTRACT_STATUS_FILTER_IN_PROGRESS: "Активные",
  CONTRACT_STATUS_FILTER_COMPLETED: "Завершённые",
  CONTRACT_STATUS_FILTER_DEFAULTED: "Просрочена",
  CONTRACT_STATUS_FILTER_CANCELLED: "Отменённые",
  DISPUTES_PAGE_TITLE: "Споры по рассрочке",
  DISPUTES_PAGE_LOADING: "Загрузка споров…",
  DISPUTES_PAGE_EMPTY: "Нет открытых споров.",
  DISPUTE_CONTRACT_LABEL: "Контракт",
  DISPUTE_REASON_LABEL: "Причина",
  DISPUTE_RESOLVE_NOTE: "Комментарий staff",
  DISPUTE_ACTION_CLOSE: "Закрыть договор",
  DISPUTE_ACTION_CANCEL: "Отменить договор",
  DISPUTE_ACTION_ADJUST: "Сдвинуть график",
  DISPUTE_ACTION_REFUND: "Частичный возврат",
  DISPUTE_PARTIAL_AMOUNT: "Сумма возврата, ₽",
  DISPUTE_RESOLVE: "Рассмотреть",
  /** @param {number} n */
  TAB_BADGE: (n) => (n > 99 ? "99+" : String(n)),
  CONTRACT_STATUS_LABEL: {
    pending_first_payment: "Ожидает первый платёж",
    active: "Активна",
    completed: "Завершена",
    defaulted: "Просрочена",
    cancelled: "Отменена",
  },
  PAYMENT_STATUS_LABEL: {
    scheduled: "Запланирован",
    due: "К оплате",
    overdue: "Просрочен",
    pending_confirmation: "Ожидает подтверждения",
    paid: "Оплачен",
  },
};
