export const PRODUCT_MODERATION_VIEW_FILTER_STALE = "stale";
export const PRODUCT_MODERATION_VIEW_FILTER_DISCOUNT = "discount";

/** @type {readonly string[]} */
export const PRODUCT_MODERATION_VIEW_FILTERS = [
  PRODUCT_MODERATION_VIEW_FILTER_STALE,
  PRODUCT_MODERATION_VIEW_FILTER_DISCOUNT,
];
